### ISSUE TITLE
Spell check

### ISSUE THREAD

**Issue by nihaals** [notion-enhancer/notion-enhancer#166]
**Problem**
Spell check is pretty broken in Notion, in fact I've *never* managed to get it to work. Some sources suggest you need a lot of text but over 1,000 words still didn't work for me

**Solution**
Implement a spell check with an editable dictionary. If the OS dictionary is used it may be slightly harder on Linux as there's less of a standard

**Alternatives**
I haven't looked into how OS dictionaries work yet. An example of a mod that does this is [BetterDiscord's SpellCheck](https://github.com/mwittrien/BetterDiscordAddons/blob/master/Plugins/SpellCheck/SpellCheck.plugin.js). Being able to install Chrome extensions could also solve this. On notion.so, [LanguageTool](https://chrome.google.com/webstore/detail/grammar-and-spell-checker/oldceeleldhonbafppcapldpdifcinji) works well (it also only checks blocks you click on) but [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen), which is *way* more popular, doesn't seem to detect the text inputs. It may also be possible to fix Notion's existing spell check

**Comment by nihaals** [comment]
[AUR notion-app](https://aur.archlinux.org/packages/notion-app/) now has spell check (possibly due to switching to a Windows-based build)

**Comment by davidbailey00** [comment]
Yes, I believe this works in the deb builder as of Notion 2.0.10 :)

**Comment by Davoleo** [comment]
Hi, has this been released yet or is it just implemented in the dev env? it'd be an awesome feature to have

**Comment by dragonwocky** [comment]
@Davoleo this should come (in theory) with any notion installation (enhanced or not) according to your OS dictionary.

**Comment by Davoleo** [comment]
oh yeah, the fact is sometimes I write in Notion using my native language and sometimes I write in English and Notion usually doesn't understand it and since my OS language is set to English it underlines all the words in another language, I don't know if there's a way to fix this OS-wise otherwise an option to specify what language a page is written in would be great

**Comment by rBatistaDev** [comment]
@Davoleo i have exactly the same problem, I use the OS in English, I write in Portuguese and the consequence is that the spell checker was totally useless.
