### ISSUE TITLE
Can't reorder Tabs widget in enhancement menu

### ISSUE THREAD

**Issue by tsweezy** [notion-enhancer/notion-enhancer#192]
**describe the bug**
When reordering enhancements in the enhancements menu, the *tabs* enhancement has a drag handle when it, I'm guessing, shouldn't.

**expected behaviour**
The *tabs* enhancement widget has a drag handle but doesn't drag to reorder. I'd suspect that since it's a core enhancement it shouldn't be draggable in the first place, someone must've just forgotten to remove the handle.

**screenshots**
![bug](https://user-images.githubusercontent.com/45302428/97902956-56eb3400-1d0c-11eb-9e4d-3ac825a19a0b.gif)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
ah, yes, ty. i'll fix that, it's not meant to be draggable.
