### ISSUE TITLE
How to make " hotkey?

### ISSUE THREAD

**Issue by yedhrab** [notion-enhancer/notion-enhancer#193]
I want to make windows display hotkey `Super+"`, how can I do this?

**Comment by dragonwocky** [comment]
#204

**Comment by dragonwocky** [comment]
have you tried setting it to that in the menu?

**Comment by yedhrab** [comment]
Yes, but when i type `super+"` doensn't work. Maybe some other id value exists for `"`. Also my keyboard layout is Turkish Q (not English)

**Comment by dragonwocky** [comment]
i know on most keyboards there's not actually a " key: it's shift+'
perhaps try setting to `Super+Shift+'`

**Comment by yedhrab** [comment]
It doesn't work
