### ISSUE TITLE
infinite loading

### ISSUE THREAD

**Issue by Saurabh-joshi** [notion-enhancer/notion-enhancer#197]
**describe the bug**
When I relaunched after enabling tabs - relaunch failed (it's just loading)
Notion is not working - can't open Enhancement window to toggle off tabs as that window is not working as well (this one is keep loading as well)
Issue got solved after ~5th relaunch - it wasn't about time as I waited ~10 minutes for one relaunch (and it didn't work) and when it worked, it (Notion) relaunched quickly

**expected behaviour**
It should work on first relaunch
I did enable tabs on the first day of the update as well, and it worked on 2nd relaunch and this time on 5th relaunch - so it never worked on first relaunch for me

**screenshots**
Both (Notion & Enhancement window) just loading infinitely

**platform**
Windows 10

**Comment by dragonwocky** [comment]
hi @Saurabh-joshi, when it next happens please do `ctrl+shift+i` and `alt+ctrl+shift+i` (in notion) and then show screenshots of anything in the "console" tab in the windows those hotkeys should open.

**Comment by chrisnatterer** [comment]
I think I experience similar crashes in tabs.

In my case it happens, when accessing a page through a link from a different page.

Screenshots of error and console log attached. Thanks for this project!
<img width="421" alt="Screen Shot 2020-11-04 at 17 19 42" src="https://user-images.githubusercontent.com/348183/98174037-2c42dc00-1ec2-11eb-86ce-24eada633f6a.png">
<img width="1626" alt="Screen Shot 2020-11-04 at 17 18 40" src="https://user-images.githubusercontent.com/348183/98174054-3238bd00-1ec2-11eb-8cc0-7c481c10b4a1.png">

**Comment by Saurabh-joshi** [comment]
Seems like the issue is gone for me. 
I tested 3 times today (toggle on the tabs -> relaunch -> toggle off -> relaunch) and it worked all 3 times as expected. 
I can also go back-and-forth as expected between backlinks, links, and linked databases

**Comment by varsha119** [comment]
> I think I experience similar crashes in tabs.
> 
> In my case it happens, when accessing a page through a link from a different page.
> 
> Screenshots of error and console log attached. Thanks for this project!
> <img alt="Screen Shot 2020-11-04 at 17 19 42" width="421" src="https://user-images.githubusercontent.com/348183/98174037-2c42dc00-1ec2-11eb-86ce-24eada633f6a.png">
> <img alt="Screen Shot 2020-11-04 at 17 18 40" width="1626" src="https://user-images.githubusercontent.com/348183/98174054-3238bd00-1ec2-11eb-8cc0-7c481c10b4a1.png">

I have the same issue

**Comment by Saurabh-joshi** [comment]
Issue (nothing opens just a blank screen loading) was not because of tabs - but a general bug. It has become even more frequent now. 
I did come up with workaround that worked for me twice today.
- Uninstall Notion enhancer
- Go to any random page in your (non-enhanced) Notion
- Install back Notion enhancer

**Comment by dragonwocky** [comment]
infinite loading in the menu is now fixed in the work-in-progress.
still working on the app itself.
