### ISSUE TITLE
Ubuntu 20.04 / POP_OS 20.04 Don't run

### ISSUE THREAD

**Issue by zozito** [notion-enhancer/notion-enhancer#203]
Hi team, I installed notion enhacer on POP_OS 20.04 and the instalarion runs as aspected but when i run i got this error:

angelo@pop-os:~$ notion-enhancer 
/usr/local/lib/node_modules/notion-enhancer/pkg/helpers.js:75
      throw new EnhancerError('nothing found: platform not supported.');
      ^

EnhancerError: nothing found: platform not supported.
    at /usr/local/lib/node_modules/notion-enhancer/pkg/helpers.js:75:13
    at Object.<anonymous> (/usr/local/lib/node_modules/notion-enhancer/pkg/helpers.js:95:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/notion-enhancer/bin.js:12:23)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

This is not compatible with Pop_OS 20.04?

After the instalation also don't create any shortcut on gnome aplications menu

Thank you

**Comment by dragonwocky** [comment]
hi @zozito, did you install notion before trying to install the notion enhancer?
this isn't a standalone app. you must have one of the supported platforms listed in the README already installed.

**Comment by bangarangler** [comment]
hey @dragonwocky .... I installed with mac no issues this morning.  Also trying to install on linux.  Leaving this here as same OS. Pop_os 20.0.4 -> i do have notion installed and running on linux.  However for the life of me I can't find the menu anywhere.  I've uninstalled and installed a few times. no errors. no issues running notion-enhancer check... things seem to be all good.  But can not find the menu anywhere and Alt+E is a def no go.  Any ideas what else I could try or where I could check if there is an error that I'm not seeing... tried running with -d listed from --help but not seeing any errors.  Thanks so much!

**Comment by zozito** [comment]
@dragonwocky sorry i didin't notice that...
@bangarangler do you have notion installed with wine? Or what method you have used?
Thank you both

**Comment by dragonwocky** [comment]
@zozito these 3 are the supported methods of installation:
- the arch linux AUR [notion-app](https://aur.archlinux.org/packages/notion-app/) package.
- the linux [notion-app](https://github.com/jaredallard/notion-app) installer.
- [@haydn-jones](https://github.com/haydn-jones/)'s fork of the
  linux [notion-deb-builder](https://github.com/haydn-jones/notion-deb-builder).

**Comment by bangarangler** [comment]
@zozito I've use notion-app installer and haydn-jone's fork of the linux notion-deb-builder both work fine.  I don't use windows at all so for me I used the above to install notion on linux.

**Comment by zozito** [comment]
@bangarangler @dragonwocky thank you i already installed
But i have the same issue as @bangarangler i don't have menu too
Thanks

**Comment by jinnzy** [comment]
> @bangarangler @dragonwocky thank you i already installed
> But i have the same issue as @bangarangler i don't have menu too
> Thanks
Me too, did you solve it

**Comment by jinnzy** [comment]
> @bangarangler @dragonwocky thank you i already installed
> But i have the same issue as @bangarangler i don't have menu too
> Thanks

Me too, did you solve it

**Comment by jinnzy** [comment]
> > @bangarangler @dragonwocky thank you i already installed
> > But i have the same issue as @bangarangler i don't have menu too
> > Thanks
> 
> Me too, did you solve it

I just reloaded Notion and can use it
