### ISSUE TITLE
empty "open extensions menu" triggers on every keypress.

### ISSUE THREAD

**Issue by LatitudeAmpere** [notion-enhancer/notion-enhancer#204]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
whenever I type anything in Notion, the enhancements menu opens

**expected behaviour**
it should only open when clicked or when the hotkeys are pressed

**screenshots**
if applicable, add screenshots of your problem.

**platform**
macOS

**Comment by dragonwocky** [comment]
hi @LatitudeAmpere, can you show me what the hotkeys are in settings?
![image](https://user-images.githubusercontent.com/16874139/98035359-7bf6b880-1e6c-11eb-80b6-7736bb3e54e7.png)

**Comment by dragonwocky** [comment]
ah, just saw discord.

**Comment by shivampotdar** [comment]
Facing the same..

**Comment by dragonwocky** [comment]
@shivampotdar yes. I know why the bug occurs, just haven't had time to patch it yet.

To reset your settings so that doesn't happen, go into your home/user folder and delete the folder named `.notion-enhancer`.

**Comment by shivampotdar** [comment]
Thanks. That helped!
