### ISSUE TITLE
Formula number formatting non-functional

### ISSUE THREAD

**Issue by filip-van-hoeckel** [notion-enhancer/notion-enhancer#211]
In calculation columns there's no way to format the number (for instance, currency symbols). When clicking the format icon in the field it opens the formula editor, instead of the format dropdown.

**platform**
Win7X64 pro

**Comment by dragonwocky** [comment]
hi, I can't reproduce this, the dropdown opens fine for me?
![image](https://user-images.githubusercontent.com/16874139/98811130-6c7efd00-2474-11eb-9270-4201e3b48262.png)

**Comment by filip-van-hoeckel** [comment]
And if your try in table view (not detail view)?
