### ISSUE TITLE
"Notion quit unexpectedly" after reboot

### ISSUE THREAD

**Issue by mtoohey31** [notion-enhancer/notion-enhancer#212]
**describe the bug**
what is the bug - what happens?

After installing notion enhancer, it works as expected, however after I reboot, it fails to open and displays the MacOS error message: "Notion quit unexpectedly". If I re-install Notion then it works just fine, even if I re-install Notion enhancer, I just can't reboot it or else it breaks.

**expected behaviour**
why is this a bug - what should be happening?

Notion-enhancer should still allow Notion to be opened after rebooting.

**screenshots**
if applicable, add screenshots of your problem.

N/A

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
MacOS 10.15.7

**Comment by bangarangler** [comment]
Exact same issue as above also happening for me with MacOS. *thumbs up*

**Comment by Adambl4** [comment]
The same happens to me aftet reboot on MacOs 10.14.6. It says `The application "Notion" can't be opened.`
Also I'm getting such error if I try open the app via CLI.
```
> open -a /Applications/Notion.app
LSOpenURLsWithRole() failed for the application /Applications/Notion.app with error -10810.
```

**Comment by santiyounger** [comment]
Save problem here are there any solutionto this issues? The only way I can solve it is by reinstalling both notion and notion enhancer from zero which gets tedious

Thanks!

**Comment by dragonwocky** [comment]
Could this be related to https://github.com/notion-enhancer/notion-enhancer/issues/355?

**Comment by caraar12345** [comment]
@dragonwocky -- definitely to do with #355. I just had this exact problem so used the `codesign` command provided as a fix by a user over there and it sorted it out instantly!

**Comment by santiyounger** [comment]
> @dragonwocky -- definitely to do with #355. I just had this exact problem so used the `codesign` command provided as a fix by a user over there and it sorted it out instantly!

thanks for the link, I'll try out that solution!
