### ISSUE TITLE
Quick find shortcut doesn't work initially with notion enhancer.

### ISSUE THREAD

**Issue by aarjav24** [notion-enhancer/notion-enhancer#218]
**Description**
When the Notion app is opened and I want to quickly find a page using the shortcut Ctrl + P, it doesn't work. However, the shortcut is fully functional without notion-enhancer. Also, if I click the "quick-find" button on the sidebar and then try the shortcut it works. Upon restarting the app, the bug reappears.

**Screenshots**
N/A

**Platform**
Windows 10 Home

**Comment by dragonwocky** [comment]
@aarjav24 is the tabs extension enabled?

**Comment by aarjav24** [comment]
@dragonwocky Yes

**Comment by aarjav24** [comment]
> @aarjav24 is the tabs extension enabled?

Yes
