### ISSUE TITLE
New tab shortcut disables shortcut to close all toggle lists.

### ISSUE THREAD

**Issue by aarjav24** [notion-enhancer/notion-enhancer#220]
**Description**
There is keyboard shortcut to toggle all lists in notion triggered by Ctrl + Alt + T. When using the tabs feature, this shortcut opens a new tab although the shortcut to do so is Ctrl + T only.

**Expected Behaviour**
Instead of opening a new tab, Ctrl + Alt + T should toggle all lists in the Notion page.

**Screenshots**
N/A

**Platform**
Windows 10 Home

**Comment by kerningium** [comment]
You can change key bindings for tabs. 
![image](https://user-images.githubusercontent.com/73218471/98446417-5a831e80-2143-11eb-9f1c-ce801d193f39.png)

**Comment by aarjav24** [comment]
> You can change key bindings for tabs. I hope this solves your problem
> 
> ![image](https://user-images.githubusercontent.com/73218471/98446417-5a831e80-2143-11eb-9f1c-ce801d193f39.png)

But then this won't allow me to use ctrl or alt keys, making it counter intuitive. Moreover, I'm facing repeated problems with the notion-enhancer, as I've mentioned [here](https://github.com/dragonwocky/notion-enhancer/issues/219), so cannot use it until a serious bug fix comes out. :(
