### ISSUE TITLE
Tables missing lines and offset

### ISSUE THREAD

**Issue by Theguyhere0** [notion-enhancer/notion-enhancer#222]
**describe the bug**
The bar between the header row and the first row in tables has gone missing in the recent update. Also, the body rows are sometimes offset compared to the header row.

**expected behaviour**
There should not be bars missing in the tables and the columns should be flush throughout all rows.

**screenshots**
![Screenshot (108)](https://user-images.githubusercontent.com/52550799/98432759-5ccb7700-2076-11eb-8217-46e2efac3c83.png)

**platform**
Windows 10

**Comment by aarjav24** [comment]
Commenting to say that I'm facing the same issue.

Windows 10 Home

**Comment by anzlechavezz** [comment]
having the same problem on MacOS 10.15.7

**Comment by dragonwocky** [comment]
#280
