### ISSUE TITLE
Create pages always with full width flag set

### ISSUE THREAD

**Issue by mariusraht1** [notion-enhancer/notion-enhancer#223]
**problem why do you need this feature?**
I always set the flag 'Full width' for each page to true manually.

**solution how do you want this feature to appear/act? do you have any suggestions for how it could be implemented?**
'Full width' flag should be enabled by default if one creates a new page.

**Comment by a13ph** [comment]
see also: https://github.com/notion-enhancer/notion-enhancer/issues/159

**Comment by dragonwocky** [comment]
can't be done. the enhancer only wraps around what you view in the app, it doesn't communicate with or modify any of the data notion stores.

so while yes, you can set up something to automatically click the "full width" flag, it wouldn't know if the page is new or not, and if you did want to make a page not full width that could prove problematic.

what you can do though is make pages appear full width by making use of the css page width variables (see https://github.com/notion-enhancer/tweaks and https://github.com/notion-enhancer/notion-enhancer/blob/dev/DOCUMENTATION.md#variablescss)
