### ISSUE TITLE
Close Sidebar

### ISSUE THREAD

**Issue by ClaireBookworm** [notion-enhancer/notion-enhancer#228]
I'm not sure if this is intentional but I can't seem to find the << button normally used to close the sidebar (and this isn't related to focus mode, because I'm not using it in full screen). Is there a built in Notion shortcut for this or some other place the button exists? Thanks!

**expected behaviour**
expected to be able to minimize sidebar

**platform**
macOS desktop app

**Comment by ClaireBookworm** [comment]
It seems this happens when you have accounts with 2 different emails -- since the account expands vertically it covers the sidebar icon. When you just have one email it shows up...

**Comment by Arecsu** [comment]
Interesting. Does this happen with vanilla Notion (no notion-enhancer installed)?
