### ISSUE TITLE
Scroll Up Icon not Found

### ISSUE THREAD

**Issue by ClaireBookworm** [notion-enhancer/notion-enhancer#230]
Not quite a major issue but the scroll up svg icon doesn't show in the bottom -- might just be an issue with file path
<img width="1209" alt="Screen Shot 2020-11-07 at 1 31 25 PM" src="https://user-images.githubusercontent.com/41759033/98451749-9abfae00-20fd-11eb-9aad-c8af45c6b27e.png">

(also, I'm on macOS)

**Comment by dragonwocky** [comment]
in this release it was a unicode symbol, the PR with the SVG was after v0.10.0
