### ISSUE TITLE
Smaller Title Bar

### ISSUE THREAD

**Issue by ElishaG** [notion-enhancer/notion-enhancer#236]
**problem**
Title bar (with tabs and buttons) is too big and takes up too much space. Doesn't look very "clean".

**solution**
Just make it smaller? Maybe just as small as the native buttons.

**alternatives (optional)**

**Comment by CarbonGhost** [comment]
I was going to make a similar issue, this is more or less my only problem with the tabs enhancement.

**Comment by ElishaG** [comment]
I was able to do this by working around the tabs.css and titlebar.css. But it would still be nice to maybe have this configurable from the enhancements window.

**Comment by weiren1998** [comment]
I am trying to figure out this problem. My result shows below. 
![image](https://user-images.githubusercontent.com/45010350/105456873-e1ff1900-5cc0-11eb-978d-934e531b5860.png)
If you want to get the same result, you can follow the steps below.
1. change the tabs.css file at *\notion-enhancer\mods\core\tabs.css
    
![image](https://user-images.githubusercontent.com/45010350/105457151-4cb05480-5cc1-11eb-8f74-85836e995af9.png)

2. change the buttons.css file at *\notion-enhancer\mods\core\css\button.css

![image](https://user-images.githubusercontent.com/45010350/105457380-b4669f80-5cc1-11eb-9d57-ab4d2901b857.png)

Maybe my answer is not such perfect, but it worked!

ps. If the emoji showed whthin the tabs is not work, you can simply remove the image and just show the title. You can change the tabs.css like this:
![image](https://user-images.githubusercontent.com/45010350/105457829-6605d080-5cc2-11eb-889c-a563bb4d8d5d.png)
