### ISSUE TITLE
Timeline View is unusable and has a visual bug

### ISSUE THREAD

**Issue by 5andu** [notion-enhancer/notion-enhancer#254]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
The newly introduced Timeline View is unusable and has a visual bug.

**expected behavior**
I should be able to add dates, drag them and reorganize them.

**screenshots**
![image](https://user-images.githubusercontent.com/38139664/99105187-5bec9500-25e2-11eb-973a-75b80510eabc.png)

**platform**
 Windows 10

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-enhancer/issues/248
