### ISSUE TITLE
the new database timeline view is not properly displayed 

### ISSUE THREAD

**Issue by alanzirpoli** [notion-enhancer/notion-enhancer#258]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
timeline view for the database is not correctly working nor displayed. Deactivate all the enhancement doesn't solve the problem.

**expected behaviour**
The timeline view is a new feature. interaction with the element of the database is broken. I'm not able to add, move or edit the elements.

**screenshots**
with notion enhancer
![image](https://user-images.githubusercontent.com/63505397/99153309-f6fb7280-26a7-11eb-93fc-b7b37a50c72c.png)

without notion enhancer
![image](https://user-images.githubusercontent.com/63505397/99153402-9caee180-26a8-11eb-9dfe-89dab7d9a4d0.png)

**platform**
windows 10

**Comment by dragonwocky** [comment]
#248
