### ISSUE TITLE
Delay to open the app

### ISSUE THREAD

**Issue by yasminweber** [notion-enhancer/notion-enhancer#263]
**describe the bug**
I've just downloaded this notion-enhancer yesterday, and today my Notion app is taking forever to start... like 20/30 minutes.
Does anybody know if it is related to the enhancer, or if there's anything I can do to fix this?

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/43188652/99194358-9e86ac80-275d-11eb-900e-8d701a17184b.png)

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
Windows 10

**Comment by joshdavies14** [comment]
I believe this is being looked into/fixed (see issue #197  as looking at the two these are the same issue?) :)
