### ISSUE TITLE
"Enhancements" stuck in loading screen

### ISSUE THREAD

**Issue by thehabdash** [notion-enhancer/notion-enhancer#264]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
When I select the menu item "Enhancements" under the icon in MacOS top menu bar, it opens a window and loading image that stays in perpetual motion. The contents of the page never load. Image below.

**expected behaviour**
I'd expect the "Enhancements" content to load when I select it from the menu.

**screenshots**
![notion-enhancer-loading-issue](https://user-images.githubusercontent.com/4616150/99200517-a4c75980-275a-11eb-8edb-4fd28aeea842.png)

**platform**
macOS Big Sur

That said, it's a great tool. Thank you for creating it!

**Comment by dragonwocky** [comment]
same issue as in #197, fix will be released soon
