### ISSUE TITLE
Toggling on Theme causes Notion to stop working

### ISSUE THREAD

**Issue by Asgardian-Lord** [notion-enhancer/notion-enhancer#269]
**Bug Desciption**
Notion is not visible. What I can see instead is a white window, with a loading icon in the centre.
I had toggled off Focus Mode, and toggled on one of the new themes. I am not able to see the enhancements menu to verify the exact name of the theme, but it was a kind of _Candy theme,_ and the description stated it had bold colours.
Immediately prior to the bug manifesting, I had disabled the _Gamer_ theme, and toggled on "tabs".

**Expected Behaviour**
I should be able to view my Notion window with all my notes, the app should generally be usable. Instead, I'm unable to interact with anything. The enhancement window is also plain white with a loading icon in the middle.

**screenshots**
This is literally how the Notion window looks like at the moment.
![image](https://user-images.githubusercontent.com/63311503/99490086-230c4180-298f-11eb-8f58-2dfb06420c38.png)

**Platform**
I'm using Windows 10, Build 20251. It's a beta build.

**Comment by dragonwocky** [comment]
see #197
