### ISSUE TITLE
macOS You do not have permission to open the application

### ISSUE THREAD

**Issue by KerwinKwong** [notion-enhancer/notion-enhancer#282]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
https://raw.githubusercontent.com/KerwinKwong/Image/main/uPic/CleanShot%202020-11-23%20at%2014.32.31@2x.png

**Comment by dragonwocky** [comment]
#253
