### ISSUE TITLE
Colored Database cells like excel or Google Sheets

### ISSUE THREAD

**Issue by madrigal1** [notion-enhancer/notion-enhancer#286]
**problem**
i am not able to set a background colour for my database cells. 
I am a student where the database cells can have a background colour to colour code my progress

**solution**
be able to choose the background colour in the database cells from the drop down menu

**alternatives (optional)**
nope havnt tried this myself

**Comment by dragonwocky** [comment]
out of scope of the enhancer's functionality (potentially possible but implementation would be a pain and would work unreliably).

additionally, while notion has tables/databases, these work differently to the spreadsheet format used elsewhere and should not be attempted to be treated as if they are the same.
