### ISSUE TITLE
White window, can't use the app

### ISSUE THREAD

**Issue by elasticnoodles** [notion-enhancer/notion-enhancer#296]
I did everything as per instructions, but the app itself just appears white, and I couldn't use it. I've already tried re-installing and redoing the enhancer, but it's just the same. I'm a Windows 10 user. 

![Screenshot 2020-12-01 163932](https://user-images.githubusercontent.com/75302455/100716558-d5aebc00-33f3-11eb-9321-daeac7886d0a.png)

**Comment by jareddantis** [comment]
+1, looks like the official client had an update today. Had to remove notion-enhancer in the meantime.

**Comment by xlangzhong** [comment]
I also meet the problem

**Comment by oriolrius** [comment]
+1

**Comment by Mara-Li** [comment]
+1 too :(

**Comment by eexxyyq** [comment]
+1 cant work (

**Comment by salah124** [comment]
same problem

**Comment by salah124** [comment]
+1 too :(

**Comment by JacobPei** [comment]
+1

**Comment by dragonwocky** [comment]
this is a known issue that will be affecting everyone. I'll get to it asap, but i am busy with some irl stuff at the moment and it might be a couple days. if all you have to contribute is "+1", then just add a reaction to the initial comment. don't fill up the thread unnecessarily.

**Comment by dragonwocky** [comment]
#298
