### ISSUE TITLE
unable to install notion enhancer 

### ISSUE THREAD

**Issue by jxishreee** [notion-enhancer/notion-enhancer#297]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
i had notion enhancer earlier on and i uninstalled it because my notion was not opening. i also deleted node.js. then i reinstalled notion and i reinstalled node.js however i am unable to run the code in terminal to install the notion enhancer. 

**expected behaviour**
unable to install the enhancer, it says "unable to find node modules no such file or directory" ; im not sure where i went wrong but i cannot find any help with reinstalling so i thought of asking for help here! thank you! 

**screenshots**
<img width="691" alt="Screen Shot 2020-12-01 at 12 22 57 PM" src="https://user-images.githubusercontent.com/75310483/100734667-4e038600-33d0-11eb-99aa-5e32981f216d.png">

**platform**
macOS

**Comment by BharathJawahar** [comment]
![image](https://user-images.githubusercontent.com/47178038/100747873-9dfe3f00-3408-11eb-8503-36fcd72f96d3.png)

Even I too have similar problem like this

**Comment by Arecsu** [comment]
This has little to do with notion-enhancer and more like to something going wrong in your computer. It can't even find the command 'chmod' nor 'npm'. There's something more going on there.
