### ISSUE TITLE
Odd shadow under Ctrl+F

### ISSUE THREAD

**Issue by kursorbyte** [notion-enhancer/notion-enhancer#299]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
The find menu (ctrl+f) has an odd-looking shadow in light mode.

**screenshots**
![Screenshot 2020-12-01 131954](https://user-images.githubusercontent.com/74338929/100780627-f1a46480-33d7-11eb-8f05-8e4b4bc7b287.png)
Disabling the following removes the shadow entirely.
![Screenshot 2020-12-01 131957](https://user-images.githubusercontent.com/74338929/100780631-f36e2800-33d7-11eb-819a-f65f22ccdc68.png)

**platform**
Windows 10, Notion enhancer v0.10.1

**Comment by dragonwocky** [comment]
the same shadow is present in an unenhanced version of notion?
![image](https://user-images.githubusercontent.com/16874139/100869736-9070b400-34f1-11eb-9933-94678d5ae0f5.png)
