### ISSUE TITLE
no such file or directory, open '/Applications/Notion.app/Contents/Resources/app.asar'

### ISSUE THREAD

**Issue by J-Ibarra** [notion-enhancer/notion-enhancer#300]
Error: ENOENT: no such file or directory, open '/Applications/Notion.app/Contents/Resources/app.asar'

**what is the bug - what happens?**
_can't install notion-enhancer_

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
![image](https://user-images.githubusercontent.com/4218738/100806611-224fc280-3407-11eb-9b4a-27577f0c86ef.png)
Folder 
![image](https://user-images.githubusercontent.com/4218738/100806715-57f4ab80-3407-11eb-88c5-b04185c2e798.png)

**platform**
Mac catalina 10.15.7

**Comment by aglalit** [comment]
Also, the Notion app doesn't start after that

**Comment by dragonwocky** [comment]
@J-Ibarra what does the folder look like after a fresh install (without running the enhancer)? is the `app` there a file or folder? if a folder, what's inside it?

**Comment by Benature** [comment]
> @J-Ibarra what does the folder look like after a fresh install (without running the enhancer)? is the `app` there a file or folder? if a folder, what's inside it?

I reinstall the Notion.app, the `app` is a folder
![image](https://user-images.githubusercontent.com/35028647/100987440-7bdffa80-3589-11eb-814b-768071ddc93c.png)

**Comment by dragonwocky** [comment]
thanks. not sure if this is related yet, but are you on the new m1 processor or using intel?

**Comment by Benature** [comment]
> thanks. not sure if this is related yet, but are you on the new m1 processor or using intel?

intel, still using macOS 10.

**Comment by Adambl4** [comment]
The same on Intel, macos 10.14.6

**Comment by slucyp** [comment]
same issue here

**Comment by flxbnx** [comment]
Also having this same issue, Intel, macos 11.0.1

**Comment by alyssasmith0328** [comment]
same on intel mac 10.15.7, catalina

I can uninstall notion & reinstall it to get it to come back up, definitely a pita though

**Comment by dragonwocky** [comment]
think this should be fixed, but if anyone who has had this issue is able to follow the [testing instructions](https://github.com/notion-enhancer/notion-enhancer/blob/dev/CONTRIBUTING.md#testing) with a fresh install of notion to make sure it is that would be great.

**Comment by Benature** [comment]
my fresh reinstall notion encounter this report
![image](https://user-images.githubusercontent.com/35028647/101189552-2e02e980-3692-11eb-8cf0-369028bd3dad.png)


```shell
(base)  ~/Documents/Github/GEEK/notion-enhancer   dev  npm link

> notion-enhancer@0.10.2-wip postinstall /Users/benature/Documents/Github/GEEK/notion-enhancer
> node bin.js apply -y

=== NOTION ENHANCEMENT LOG ===
 ...backing up default app.
 ...recording enhancement version.
 ~~ success.
=== END OF LOG ===
npm notice created a lockfile as package-lock.json. You should commit this file.
added 29 packages from 58 contributors and audited 29 packages in 10.638s
found 0 vulnerabilities

/usr/local/bin/notion-enhancer -> /usr/local/lib/node_modules/notion-enhancer/bin.js
/usr/local/lib/node_modules/notion-enhancer -> /Users/benature/Documents/Github/GEEK/notion-enhancer
```

```shell
(base)  ~/Documents/Github/GEEK/notion-enhancer   dev  notion-enhancer apply -y
=== NOTION ENHANCEMENT LOG ===
 ...backing up default app.
 ...recording enhancement version.
 ~~ success.
=== END OF LOG ===
```

**Comment by Benature** [comment]
> think this should be fixed, but if anyone who has had this issue is able to follow the [testing instructions](https://github.com/notion-enhancer/notion-enhancer/blob/dev/CONTRIBUTING.md#testing) with a fresh install of notion to make sure it is that would be great.

I followed the instructions, it's ok, notion.app can be opened normally after `notion-enhancer apply -y`

**Comment by VinSpee** [comment]
@dragonwocky the testing instructions worked for me - i think it's fixed.

**Comment by Benature** [comment]
Yes, I tested to insert a customer js and hide the help circle.

**Comment by slucyp** [comment]
It works now, thanks! @dragonwocky

**Comment by alyssasmith0328** [comment]
Yes working for me as well! Thank you a bunch for the quick fix all.
