### ISSUE TITLE
White Screen On Startup

### ISSUE THREAD

**Issue by Blueder** [notion-enhancer/notion-enhancer#303]
**describe the bug**
what is the bug - what happens?
- Everything installed normally, but when opened, notion is blank white
- Ctrl+Shift+I or F12 doesn't seem to open the console
- I reinstalled both notion, the extension, and node.js, same outcome

**expected behaviour**
why is this a bug - what should be happening?
It supposed to let me use the app... Something went completely wrong

**screenshots**
if applicable, add screenshots of your problem.
https://ibb.co/8gGZHG0

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
Windows 10 Pro

**Comment by Kimeru29** [comment]
It's happening to me too, however, I do can open the console.

![image](https://user-images.githubusercontent.com/31755035/100903541-a6e42480-348b-11eb-9659-6cf241d5533a.png)

reinstalled notion and notion-enhancer already and still nothing.

**Comment by srndko** [comment]
Me too!!.

**Comment by oroshi-tom** [comment]
I'm getting the exact same error.

**Comment by not-AMM** [comment]
Same. This started after the 'Timelines' Update of Notion -for me-. Before there were some visual bugs, but now this.

**Comment by joshdavies14** [comment]
This is a known issue - see #298
