### ISSUE TITLE
版本：Notion Setup 2.0.11

### ISSUE THREAD

**Issue by While4** [notion-enhancer/notion-enhancer#307]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

**Comment by dragonwocky** [comment]
not really sure what this means but looks like it's related to #300/#298
