### ISSUE TITLE
Notion won't start (white screen) after last update

### ISSUE THREAD

**Issue by OrelBenny** [notion-enhancer/notion-enhancer#310]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Notion won't start after updating to the last version of the enhancer. I tried to reinstall the enhancer (and even Notion itself) yet the issue continues. While uninstalling the enhancer, Notion works as usual. 

**expected behaviour**
the enhancer should work as usual. 

**screenshots**
![2020-12-03 17_52_25-Window](https://user-images.githubusercontent.com/74361304/101053368-5e625f00-3590-11eb-9bb3-0e3a1cccf244.png)

**platform**
Windows 10

**Comment by joshdavies14** [comment]
Known issue - #298
