### ISSUE TITLE
keyboard shortcuts do not work with the shift key

### ISSUE THREAD

**Issue by CloudHill** [notion-enhancer/notion-enhancer#311]
**describe the bug**
if you set the shift key as a modifier in a keyboard shortcut (e.g. set open enhancements menu to `Alt+Shift+E`), the key event is not detected.

this is because the `toKeyEvent` function does not capitalize `key` when `shiftKey` is `true`, while `KeyboardEvent` does.

this also happens with symbols (e.g. `Alt+Shift+\`) but can be worked around by setting the hotkey to it's shift counterpart (`Alt+Shift+|`).

**expected behaviour**
the shift key should work as a modifier, maybe by comparing lowercase versions of the `key` property, or by comparing just the `code` property.

**screenshots**
![image](https://user-images.githubusercontent.com/54142180/101137779-ec4a5280-3641-11eb-9877-4fd1936793ec.png)
`hotkey` is set to `Alt+Shift+E`

**platform**
windows 10

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-enhancer/issues/191
