### ISSUE TITLE
Loading tabs freezing  

### ISSUE THREAD

**Issue by djmobapps** [notion-enhancer/notion-enhancer#312]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
I had activated tabs functionality but I can't open any page. Still freezing loading page. See ss  

**expected behaviour**
Show current page

**screenshots**
![image](https://user-images.githubusercontent.com/10756057/101156342-c1073980-3628-11eb-9329-36428c8b5660.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
same cause as #298, awaiting release
