### ISSUE TITLE
after I reboot, it fails

### ISSUE THREAD

**Issue by abdullah-saadeddin** [notion-enhancer/notion-enhancer#326]
**describe the bug**
After installing notion enhancer, it works as expected, however after I reboot, it fails to open and displays the MacOS error message: "Notion quit unexpectedly". If I re-install Notion then it works just fine

**platform**
macOS 11.0.1

**Comment by dragonwocky** [comment]
try the solution here: https://github.com/notion-enhancer/notion-enhancer/issues/253#issuecomment-726599368

**Comment by abdullah-saadeddin** [comment]
it works perfect thank for your time
