### ISSUE TITLE
Tabs: Font size too large 

### ISSUE THREAD

**Issue by MaaxGr** [notion-enhancer/notion-enhancer#330]
**problem**

font-size for tabs too large in my opinion. Some text is not readable. The text-size should be smaller or equal to breadcrumb, so that it is less distracting. 
![image](https://user-images.githubusercontent.com/43404580/101341854-9d86fd80-3879-11eb-94d3-ba52bceff0ed.png)

This is present for Arch Linux notion-enchancer aur in version v0.10.2

**solution**

decrease font-size in source code

**cons**

no cons from my perspective

**alternatives**

allow an option to change font-size in settings.

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-enhancer/issues/186
