### ISSUE TITLE
zsh: command not found: npm

### ISSUE THREAD

**Issue by Robin-lems** [notion-enhancer/notion-enhancer#334]
**describe the bug**

Notion Enhancer has been working super well for 1 month but today, the app (Notion) crashed. 
I desintalled it. 
removed the packages with the command.
 Reinstalled the app.
 rerun the commands for installation but at the final command "zsh: command not found: npm" I have this message. 
I'm on mac. 

I really don't know what to do. I had a message that inform me of an update and to run a command to update but it didn't worked. 

I don't really have any coding background or anything, so any help would really be well appreciated. Thanks a lot !

**Comment by dragonwocky** [comment]
this isn't an issue with the enhancer, something else has updated or gone missing on your computer - try reinstalling node.js, then running `npm i -g notion-enhancer` again. if that doesn't work, try the solution from https://stackoverflow.com/questions/12743928/command-not-found-after-npm-install-in-zsh to fix npm before attempting to install the enhancer again.

**Comment by Robin-lems** [comment]
It worked ! Thank you very much.
