### ISSUE TITLE
White Notion Window

### ISSUE THREAD

**Issue by rncyy** [notion-enhancer/notion-enhancer#338]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
When the enhancer is applied, Notion appears as a white window, including the enhancements window

**expected behaviour**
Notion should show me my notes after opening

**screenshots**
WITH ENHANCER
![image](https://user-images.githubusercontent.com/68918189/101630098-5e190680-3a5d-11eb-85ac-569335247cef.png)

WITHOUT ENHANCER 
![image](https://user-images.githubusercontent.com/68918189/101630423-d089e680-3a5d-11eb-8357-43b0ff32463d.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
are you using the latest versions of both the enhancer (v0.10.2) and notion (v2.0.11)?

**Comment by rncyy** [comment]
I double checked the versions of both apps and my notion client was outdated thanks for the quick response
