### ISSUE TITLE
Wish adding font size part

### ISSUE THREAD

**Issue by wsczh** [notion-enhancer/notion-enhancer#346]
**problem**

Wish add a function that the user can change the font size, such as the content in the page, the content in the code part.
The font size of the code part in the notion is too small, it's not so comfortable to read it. 

**solution**

**cons**

**alternatives**

**Comment by admiraldus** [comment]
if @dragon approves, i can make a module similar to font chooser module for this request.

**Comment by dragonwocky** [comment]
@wsczh you can use the custom inserts extension and change the font size css variables (see https://github.com/notion-enhancer/notion-enhancer/blob/dev/mods/core/variables.css#L42-L50) to do this already.

@admiraldus hold off on that, i have a plan for something that will do this and more already
