### ISSUE TITLE
One click highlighter-colour change

### ISSUE THREAD

**Issue by MedBlueprint** [notion-enhancer/notion-enhancer#359]
Hey, dragon. As a medical student who takes most of the notes and research works in notion, I NEED to colour-code my notes while revising and to make it more accessible. But I find notion's default highlighting process really unfriendly. 
For example, whenever I need to change the colour of my highlighters, say red to yellow 
I need to -

1.select the text 
2. a menu pops up, need to go to text colour 
3. change as needed
and if I need to use the red highlighter again, gotta repeat from 1-3 steps!

So fluent highlighting with 2-3 coloured highlighters becomes completely impractical.

In this case, instant highlighter colour palette would be a handy enhancement that may improve the quality of my life. & I believe that will be the same for many students and researchers too.

**feature-request: While text typing/editing, if the mouse cursor is put on the bottom right corner of notion window, a colour palette would pop out nearby for a one-click change of text colour/highlighter colour.**

![color palette](https://user-images.githubusercontent.com/75526224/103079911-0226b400-45ff-11eb-8529-a988673633d5.jpg)

**Comment by dragonwocky** [comment]
out of scope. until the enhancer has API access, it cannot change page content - that includes formatting.
