### ISSUE TITLE
Replacement shortcut for toggle all in list (Ctrl/Cmd+Alt+T) 

### ISSUE THREAD

**Issue by jmilldotdev** [notion-enhancer/notion-enhancer#371]
**problem**

The use of the alt key for Notion Enhancer features hijacks the Notion shortcut for opening/closing all toggles on a page (Ctrl/Cmd+Alt+T)

**solution**

Add an enhancement which allows re-binding of this shortcut

**cons**

None afaik

**alternatives**

None really, it's a fairly simple feature I think, especially if other keybinds can be shifted around.

**Comment by dragonwocky** [comment]
shortcuts added by the enhancer can already be changed. shortcuts part of notion by default can't be modified by the enhancer.

**Comment by jmilldotdev** [comment]
So there's no way around this? Unfortunate because it's the single Notion shortcut that uses the alt key...

**Comment by jmilldotdev** [comment]
Actually I'm not sure why but the shortcut does still work, it just was not working in the page I was trying it in.
