### ISSUE TITLE
EACCES -13 on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by llgdd** [notion-enhancer/notion-enhancer#372]
**describe the bug**
After installing Notion app provided by `notion-deb-builder`, I tried `npm i -g notion-enhancer`, but unfortunately it gave me an EACCES -13 error. I also tried running `notion-enhancer apply` afterwards getting the same error.

Output of `npm i -g notion-enhancer`:
```
-> npm i -g notion-enhancer     
/home/legeon/.nvm/versions/node/v14.15.1/bin/notion-enhancer -> /home/legeon/.nvm/versions/node/v14.15.1/lib/node_modules/notion-enhancer/bin.js

> notion-enhancer@0.10.2 postinstall /home/legeon/.nvm/versions/node/v14.15.1/lib/node_modules/notion-enhancer
> node bin.js apply -y

=== NOTION ENHANCEMENT LOG ===
 ...backing up default app.
### ERROR ###
file access forbidden - try running "sudo chmod -R a+wr /usr/lib/notion-desktop/resources/app.bak" , and make sure path(s) are not open.
=== END OF LOG ===
+ notion-enhancer@0.10.2
added 30 packages from 60 contributors in 9.537s
```

Output of `notion-enhancer apply -d`:

```
-> notion-enhancer apply -d                                    
=== NOTION ENHANCEMENT LOG ===
 ...backing up default app.
### ERROR ###
[Error: EACCES: permission denied, mkdir '/usr/lib/notion-desktop/resources/app.bak'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/notion-desktop/resources/app.bak'
}
=== END OF LOG ===
```

I can't `sudo chmod -R a+wr /usr/lib/notion-desktop/resources/app.bak` because there's no such file or directory.

**expected behaviour**
I expect it to install and function properly.

**platform**
Ubuntu 20.04 LTS, Node v14.15.1, NPM v6.14.11, Notion (notion-deb-builder) v2.0.11

**Comment by AngeloChen14** [comment]
same error here

**Comment by dragonwocky** [comment]
@AngeloChen14 @llgdd try `sudo chmod -R a+wr /usr/lib/notion-desktop/resources`

**Comment by llgdd** [comment]
It's working so far. Thanks @dragonwocky!

```
=== NOTION ENHANCEMENT LOG ===
 ...backing up default app.
 ...recording enhancement version.
 ~~ success.
=== END OF LOG ===
```

**Comment by llgdd** [comment]
Closing this issue.
