### ISSUE TITLE
Did all the procedures in MacOs BigSur v11.1. Still not working

### ISSUE THREAD

**Issue by rgsaura** [notion-enhancer/notion-enhancer#373]
I tried to install following the procedure:

> installation
> if you are updating from v0.7.0 or earlier, things have changed, more information is available in this update guide. please read that before following these instructions.
> 
> ensure that no notion windows/processes are running by ending all Notion processes in your task manager.
> CMD + ALT + ESC on mac and CTRL + SHIFT + ESC on windows/linux to open task manager.
> install node.js
> you may need to restart your computer.
> notion-enhancer will use node.js, you do not need to interact with it aside from downloading to install notion-enhancer.
> open your computer's terminal, not the node.js command prompt.
> windows 10: search in your start menu (click windows key or icon in bottom left of screen) for 'cmd' or 'command prompt'.
> mac: search in spotlight (magnifying glass in top right of screen) for 'terminal'.
> type and enter the following line(s) based on your operating system, if there are multiple lines, make sure to enter them one by one .
> windows 10:
> npm i -g notion-enhancer
> mac: this may ask you to enter your password, instead of hiding your password with *** symbols, mac terminal hides it by making it invisible. simply type your password and click enter.
> sudo chmod -R a+wr /usr/local/lib/node_modules
> sudo chmod -R a+wr /usr/local/bin
> sudo chmod -R a+wr /Applications/Notion.app/Contents/Resources
> npm i -g notion-enhancer
> debian/ubuntu, chromeOS, wsl (to modify the win10 app):
> bash curl -sL https://deb.nodesource.com setup_current.x | sudo -E bash -
> sudo apt-get install -y nodejs
> npm i -g notion-enhancer
> arch linux, manjaro:
> install the aur package with your aur helper (e.g. yay -S notion-enhancer).

It didnt worked so i tried this solution proposed by rafaelosoto:

> codesign --force --deep --sign - /Applications/Notion.app

Didnt worked either.
It says that its installed, but when i open the app it shows up as normal, i tried cmd: opn+E, and nothing happens. No apparent changes anywhere.

Please someone help.

**Comment by rgsaura** [comment]
Okey, found somefind. The cmd: opt+E is still not working. But I found in my menu bar the notion enhancer icon! It was hidden at the end of all my other apps/plugins... Seems to be working. Cmd still not working.

**Comment by LFR-LFR** [comment]
Got the same problem. Where exactly did you find the notion enhancer icon? Everything applied and everything also appears in the resources folder. e.g. Changes to the renderer index.html do not affect anything...

**Comment by rgsaura** [comment]
> Got the same problem. Where exactly did you find the notion enhancer icon? Everything applied and everything also appears in the resources folder. e.g. Changes to the renderer index.html do not affect anything...

Hey! I recommend using "bartender 4". The icon is hidden at the end, overlapping with the "normal" menu bar. If you have a lot of plugins, like i do, this happens. With the bartender app you can find it. good luck!
