### ISSUE TITLE
Notion instant crash after restarting the computer

### ISSUE THREAD

**Issue by ajmnz** [notion-enhancer/notion-enhancer#374]
**Describe the bug**
Notion crashes instantly after restarting the computer. Works fine when installed, but after restarting the computer Notion won't even open.

**Expected behaviour**
Notion should open without crashing, as it does when the computer hasn't been restarted.

**Screenshots**
Error log [here](https://pastebin.com/CwtbvTgZ).

**Platform**
Macbook Pro Late 2018 15inch, running macOS Big Sur 11.1
Latest Notion version (2.0.11)
Latest notion-enhancer version (0.10.2)

**Comment by ajmnz** [comment]
Same as #285. Reinstalling both Notion or notion-enhancer doesn't solve the issue.

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/355
