### ISSUE TITLE
Integrated titlebar disappears

### ISSUE THREAD

**Issue by shahiljain** [notion-enhancer/notion-enhancer#377]
**describe the bug**
The integrated titlebar icons (close, minimize, window) disappear. Other titlebar related enhancements like topbar icons and always on top also disappear or are disabled. I have found that disabling themes can fix the bug. If you enable a theme again the titlebar works untill next relaunch.

**expected behaviour**
They should all be visible (since they all show enabled in enhancements)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/366 (fix in there)
