### ISSUE TITLE
Custom emoji (as a link or uploaded file)

### ISSUE THREAD

**Issue by patsok** [notion-enhancer/notion-enhancer#381]
**problem**

It's not really a problem but a clarity thing. I don't know if this can be implemented so I would like to ask - is there any way to set custom emoji? I have a dashboard with linked text (outside of notion - in my case courses i attend e.g. udemy) and I want to have an icon in front of it. Uploading icon/emoji as image is limited to minimum size which is too big. And to have something before the text, Notion only allows using standard emoji sets + enhancements from you guys but I prefer to set my custom icon.

**solution**

Blocking image minimum size isn't a solution because it's hard to position or even impossible. 
I would like to have an option to upload my icon (or as a link) to behave like emoji. Don't know how it could be implemented or is it possible to do it in easy way.

**cons**

Don't know, maybe higher usage? 

**alternatives**

Can't think any other way to bypass this. If it is possible in basic Notion, please tell me :D

**Comment by dragonwocky** [comment]
the notion icons extension lets you add an extra library of images in to pick as page icons, but in terms of emojis that can be typed within blocks, there's no custom image solution yet.

**Comment by patsok** [comment]
Yeah, icons can be uploaded. Just want to be sure there isn't any solution yet to make this:
![obraz](https://user-images.githubusercontent.com/23488255/105362441-30e27b00-5bfb-11eb-9818-5dae30b6eaf8.png) (pages outside of notion - emojis)
look like this 
![obraz](https://user-images.githubusercontent.com/23488255/105362490-40fa5a80-5bfb-11eb-804f-cc9d5efe0224.png)(pages in notion - custom icons)

**Comment by dragonwocky** [comment]
yeah, there isn't.
