### ISSUE TITLE
Tab Title

### ISSUE THREAD

**Issue by dmercado2001** [notion-enhancer/notion-enhancer#389]
**describe the bug**
When I first installed the enhancer, all tabs I had would have titles. Then suddenly I'm not sure what happened, I may have tried to change the theme or something, but suddenly all of the titles of the tabs were gone. I checked everything to see if something was toggled on/off when it shouldnt be and nothing, I didnt find anything. the tabs toggle is still on and I haven't touched anything in that area other than making the tab select modifier command rather than Alt
<img width="477" alt="Screen Shot 2021-01-25 at 10 30 30 PM" src="https://user-images.githubusercontent.com/77819039/105796477-ef383400-5f5c-11eb-8806-9fd6e9836d6a.png">

**expected behaviour**
this may or may not be a bug and perhaps there is a toggled feature that I wasn't aware about, but each of the tabs is supposed to have the title of the page. right now they all say "notion.so"

**screenshots**
a screenshot of the tab bar is attached. they all say "notion.so" rather than the name of the page I am on, which is how it was when I first downloaded the enhancer
<img width="1000" alt="Screen Shot 2021-01-25 at 10 27 09 PM" src="https://user-images.githubusercontent.com/77819039/105796262-7802a000-5f5c-11eb-9576-a2d628533da4.png">

**platform**
macOS

**Comment by dmercado2001** [comment]
This bug is the same as #271 and #196

**Comment by dmercado2001** [comment]
I am operating on MacOS Big Sur 11.1
There is a possibility this change happened when there was an update from Big Sur 11.0 to 11.1

**Comment by dmercado2001** [comment]
<img width="1440" alt="Screen Shot 2021-01-26 at 3 33 32 PM" src="https://user-images.githubusercontent.com/77819039/105901829-dc207500-5feb-11eb-8f73-f87e6a0a01d9.png">
as stated in #200 asking for devtools consoles in #196, this is what I get

**Comment by netanelravid** [comment]
I have the same issue (Mac Catalina 10.15.7)

**Comment by kirbykatie** [comment]
Same issue - Catalina 10.15.1

**Comment by dmercado2001** [comment]
I just downloaded the new update and I am now able to see tab titles again! However, I used to be able to see them all with the icon of the notion page. Now, only the one with the custom icon shows up in the tab, but all others just have a name
<img width="1021" alt="Screen Shot 2021-02-10 at 2 59 53 AM" src="https://user-images.githubusercontent.com/77819039/107481375-0e81b480-6b4c-11eb-8c21-742be2681e58.png">

**Comment by martyns0n** [comment]
> I just downloaded the new update and I am now able to see tab titles again! However, I used to be able to see them all with the icon of the notion page. Now, only the one with the custom icon shows up in the tab, but all others just have a name
> <img alt="Screen Shot 2021-02-10 at 2 59 53 AM" width="1021" src="https://user-images.githubusercontent.com/77819039/107481375-0e81b480-6b4c-11eb-8c21-742be2681e58.png">

But what you did? And which version you have now?

I have notion-enhancer 10.2 with Macos Big Sur 11.2 but still same issue

**Comment by dmercado2001** [comment]
@martyns0n I updated my Mac to the Big Sur 11.2.1 update and have the latest version of the notion enhancer. I had deleted the Notion app and the enhancer then installed it again, and it started working again. Then what would happen is that when I would open the app, it would show up with tab titles the first about 5 tabs I'd open, then there'd be like a lapse and it would say "notion.so" then it would show the titles again after a few more tries. Now though, it went back to being just "notion.so" again. I've tried force quitting the app and reopening it, opening a bunch of tab titles, and nothing :/

**Comment by dmercado2001** [comment]
ok so very interesting but I just clicked "Reset App & Clear Local Data" when you click on the top left where it says "Notion" because the app is open, and it reset everything and I had to log in from my browser again, but when I went back in the tab titles were back. However, the icon you see for my "School!!" tab is actually showing up for the wrong page, and a lot of pages aren't properly loading. They have huge question marks on it. When I opened a new tab, the page name and notion.so were spazzing and changing back and forth very quickly. It also didn't load with the custom theme and font I put in.

<img width="1085" alt="Screen Shot 2021-02-11 at 10 25 47 AM" src="https://user-images.githubusercontent.com/77819039/107657806-82f34b00-6c53-11eb-8e7a-b68378d4e570.png">

Then I force quit the app and re-opened it, and the custom font and theme were back, and everything loaded properly. The only thing that stayed was the wrong icon for Headquarters
<img width="1075" alt="Screen Shot 2021-02-11 at 10 29 46 AM" src="https://user-images.githubusercontent.com/77819039/107658375-12006300-6c54-11eb-8bb5-dacc07bb07a1.png">

So maybe
1. resetting app data
<img width="275" alt="Screen Shot 2021-02-11 at 10 30 49 AM" src="https://user-images.githubusercontent.com/77819039/107658542-378d6c80-6c54-11eb-81a1-190eb7821cb0.png">
2. logging back in
3. force quitting notion
4. reopening Notion
will help fix the problem

This may be a temporary fix to the bug, however.

**Comment by dmercado2001** [comment]
And now I realized that:
- whenever I hide the side bar, I get the following error message (screenshot below), which goes away as soon as I open a new tab, and I go back to the same page I was working on. but once I hide the side bar, the title becomes "notion.so"
<img width="377" alt="Screen Shot 2021-02-11 at 10 49 20 AM" src="https://user-images.githubusercontent.com/77819039/107660979-cd29fb80-6c56-11eb-9c87-1f82d1231f84.png">

- however, when I pop the side bar back out, the titles to the tabs actually come back

side note: the little arrows at the top right of the side bar disappear for me and are rarely there. the only way I can hide and unhide the side bar is by going to where the side bar and is and by hovering over the very edge until the cursor changes to the double headed arrow and vertical line for dragging symbol, and clicking once to do either action.

**Comment by BaptisteBBB** [comment]
Same issue re tabs title showing "notion.so"
I'm running macOS 10.14.6
Notion 2.0.8
Notion Enhancer 0.10.2

**Comment by stutterrrrer** [comment]
same issue. 
Big Sur 11.5.1
Notion Enhanced 2.16-2



> ok so very interesting but I just clicked "Reset App & Clear Local Data" when you click on the top left where it says "Notion" because the app is open, and it reset everything and I had to log in from my browser again, but when I went back in the tab titles were back. However, the icon you see for my "School!!" tab is actually showing up for the wrong page, and a lot of pages aren't properly loading. They have huge question marks on it. When I opened a new tab, the page name and notion.so were spazzing and changing back and forth very quickly. It also didn't load with the custom theme and font I put in.
> 
> <img alt="Screen Shot 2021-02-11 at 10 25 47 AM" width="1085" src="https://user-images.githubusercontent.com/77819039/107657806-82f34b00-6c53-11eb-8e7a-b68378d4e570.png">
> 
> Then I force quit the app and re-opened it, and the custom font and theme were back, and everything loaded properly. The only thing that stayed was the wrong icon for Headquarters
> <img alt="Screen Shot 2021-02-11 at 10 29 46 AM" width="1075" src="https://user-images.githubusercontent.com/77819039/107658375-12006300-6c54-11eb-8bb5-dacc07bb07a1.png">
> 
> So maybe
> 
> 1. resetting app data
> 
> <img alt="Screen Shot 2021-02-11 at 10 30 49 AM" width="275" src="https://user-images.githubusercontent.com/77819039/107658542-378d6c80-6c54-11eb-81a1-190eb7821cb0.png">
> 
> 2. logging back in 3. force quitting notion 4. reopening Notion will help fix the problem
> This may be a temporary fix to the bug, however.

I tried your solution and it worked for a while then I found another issue where in each window only the first tab would show title and icon correctly.
What worked for the subsequent tabs is to go to the first tab where title is displaying correctly, then find the page link in that tab, (be it in the sidebar or somewhere else in the page) then command-click the link, which opens that in a new tab where the tab title would work fine.
But this is still hit-and-miss; thought should post this workaround here.

**Comment by stutterrrrer** [comment]
another hit-and-miss workaround is to command-shift-N to open a new window where the first tab is showing page title, then drag that tab over to drop in the previous window, and the dropped tab might retain the title.
