### ISSUE TITLE
The title bar button (minimize, maximize and close) are bugged out and zoomed in

### ISSUE THREAD

**Issue by limittox** [notion-enhancer/notion-enhancer#390]
**describe the bug**
The title bar button are appear to be much much bigger than what they are supposed to be. Almost 500% scale.

**expected behaviour**
Title bars are supposed to be much smaller.

**screenshots**
![image](https://user-images.githubusercontent.com/26973332/105935053-65e04900-60a5-11eb-8de1-9930c7ac5dfa.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/291
