### ISSUE TITLE
I cannot change theme.

### ISSUE THREAD

**Issue by tony13382** [notion-enhancer/notion-enhancer#392]
**describe the bug**
I cannot change theme.

**expected behaviour**
I chose the theme and reboot software. But it isn't changed.

**screenshots**
![Snipaste_2021-01-27_23-40-43](https://user-images.githubusercontent.com/21279459/106015105-1a578a80-60f9-11eb-9879-7be87a8a6efa.png)

**platform**
windows 10

**Comment by dragonwocky** [comment]
do you by any chance have the night shift extension on?

notion is updating their theming at the moment which is breaking a lot of the enhancer.

**Comment by vedantmamgain** [comment]
I have the same issue the theme isn't changing/

**Comment by dragonwocky** [comment]
dark mode themes will not work if notion is in light mode. change it to dark mode (settings -> appearance).
