### ISSUE TITLE
I install notion with scoop in my windows computer ,how can I use the tool?

### ISSUE THREAD

**Issue by orzgeelam** [notion-enhancer/notion-enhancer#393]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

**Comment by dragonwocky** [comment]
you cant. these are the official installers: https://github.com/notion-enhancer/notion-enhancer#supported-desktop-clients
