### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by l782993610** [notion-enhancer/notion-enhancer#395]
In the console it reports
![image](https://user-images.githubusercontent.com/59809602/106150527-687e9380-61b6-11eb-90bd-984bf754d2d2.png)

![image](https://user-images.githubusercontent.com/59809602/106150827-b2677980-61b6-11eb-8e5c-7c72acc08348.png)

Win10 on surface pro 5; Nodejs at 15.7.0; Enhancer at v0.10.2

**Comment by dragonwocky** [comment]
dup of #291
