### ISSUE TITLE
[urgency] Windows button too big，Can I submit photos at here?

### ISSUE THREAD

**Issue by illegiblescholar** [notion-enhancer/notion-enhancer#396]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

**Comment by dragonwocky** [comment]
dup of #291
