### ISSUE TITLE
File name for photos

### ISSUE THREAD

**Issue by Kris092** [notion-enhancer/notion-enhancer#397]
**problem**

Currently I'm studying art history and I collect all my paintings inside notion. I have to manually name caption of each photo. 

**solution**

Show file Name under the photo/ file. 

**cons**

I don't see any. 

**alternatives**

Yes I could use finder but in Notion I can access all notes from phone which is big advantage.

**Comment by caraar12345** [comment]
surely you'd continue to have this issue on your phone? 😄

**Comment by dragonwocky** [comment]
yup. the enhancer can't affect mobile.
