### ISSUE TITLE
[feature request] Disable "Type / for commands" prompt 

### ISSUE THREAD

**Issue by huriprasath** [notion-enhancer/notion-enhancer#401]
**problem**
The "**Type '/' for commands**" prompt appearing on every new line is really distracting and I think a [lot](https://twitter.com/dkislyuk/status/1129763552942874625?s=20) [of](https://twitter.com/notionhq/status/1106679673386196992?lang=en) [people](https://www.reddit.com/r/Notion/comments/jzrxcp/anyway_to_turn_off_the_type_for_commands_grey_text/) will agree about this. 
![image](https://user-images.githubusercontent.com/10820205/106573899-3b3c3780-6560-11eb-9cc6-21b0d84956cd.png)

**solution**
An option to disable the prompt would be really useful.

**cons**
Users might not realise the shortcut exists. But if the user knows enough to use notion-enhancer to disable the prompt, then they probably already know about the / shortcut.

**alternatives**
None.

**Comment by huriprasath** [comment]
Implemented this [using custom-inserts](https://github.com/notion-enhancer/tweaks/blob/main/tweaks/remove%20type%20for%20commands.md) with the following CSS: 
```css
/* ========== REMOVE TYPE FOR COMMANDS ========== */
[contenteditable]:empty:before {
  display: none !important;
}```

**Comment by huriprasath** [comment]
This custom CSS does not seem to be working after the last update (Notion v 2.0.16). Not sure why.

> Implemented this [using custom-inserts](https://github.com/notion-enhancer/tweaks/blob/main/tweaks/remove%20type%20for%20commands.md) with the following CSS:
> 
> ```css
> /* ========== REMOVE TYPE FOR COMMANDS ========== */
> [contenteditable]:empty:before {
>   display: none !important;
> }
> ```

**Comment by dragonwocky** [comment]
try `:after` instead of `:before`

**Comment by huriprasath** [comment]
> try `:after` instead of `:before`

That worked. Thank you :)
