### ISSUE TITLE
Subscript and Superscript

### ISSUE THREAD

**Issue by dmercado2001** [notion-enhancer/notion-enhancer#403]
**problem**
why is this feature necessary? how will it help? what existing shortcomings does it address?

I would say it would help a lot with regualrly typing in with sub and superscript. Right now to be able to do that, you would have to try to do a math formula, but it would be beneficial to have a sort of shortcut to be able to type with sub and superscript. Sometimes will taking notes, there may be symbols that have sub or superscript, and it's much easier to just type it out rather than have to do through making a "math equation."

_Long story short: facilitates notetaking_

**solution**
how will this feature appear/act? how could this be technically implemented using the available
capabilities of the enhancer and notion?

it would just look and act like regular sub and super script. Just text that is smaller and slightly above or below the normal text. I don't know anything about the technological aspects of how to do that.

**cons**
what are the potential costs or dangers of this feature, or things that may go outside of the enhancer's scope? e.g. bad performance, security issues, or modifying the data notion stores.

I don't see any potential cons. It doesn't see like the most elaborate enhancer, all the other things that are there seem way more difficult. But again, I also don't know anything about that.

**alternatives**
would a different feature remove the need for this? does this need to be implemented by the enhancer? could an external service work better? e.g. playing background music via noisli or youtube.

I don't think this can be subed in externally except by the math equation feature I guess. But even then, the math equation thing is in a different font, so it won't look like part of the text. All in all I don't see it potentially interupting any current feature, and it's something that would specifically need to be done by the enhancer, or by notion itself.

**Comment by dragonwocky** [comment]
adding any *new* formatting options or block types is out of scope - the enhancer can only modify the ones already available. you could use custom css to e.g. make text of a certain colour act as super/subscript, but not add an additional formatting option, unfortunately.

**Comment by Trxnks** [comment]
really need this
