### ISSUE TITLE
Custom Font for Math Equation

### ISSUE THREAD

**Issue by dmercado2001** [notion-enhancer/notion-enhancer#404]
**problem**
why is this feature necessary? how will it help? what existing shortcomings does it address?

I wouldn't say it's a necessity, but it would definitely allow for more customization of notes. It addresses the shortcoming of customizability of math equations in notes and such.

**solution**
how will this feature appear/act? how could this be technically implemented using the available
capabilities of the enhancer and notion?

It will appear as a math equation with a customized font. It could be implemented same as the other customized fonts, in that same place where we input the name of the font.

**cons**
what are the potential costs or dangers of this feature, or things that may go outside of the enhancer's scope? e.g. bad performance, security issues, or modifying the data notion stores.

I don't forsee any potential costs, dangers, or difficulties.

**alternatives**
would a different feature remove the need for this? does this need to be implemented by the enhancer? could an external service work better? e.g. playing background music via noisli or youtube.

I don't see any other way to customize the math font. Even when customizing the regular fonts, the math font still comes out the same.

**Comment by mtoohey31** [comment]
Ok, so I don't quite understand the method being used for the current font changer, but I've dug into the css and come up with [this mod here](https://github.com/mtoohey31/notion-enhancer/commit/11514ee7f065df31ea02503e9f4115037b68dc74), which is hard-coded to Fira Math. If you don't mind getting your hands a little dirty, it should be pretty trivial to change all the mentions of Fira Math to your desired font and apply it. When I have time I may see if I can add math options to the main font switching mod, or create a separate font switching mod that allows you to choose what font you want to use, I'd like to use this for a little bit before I do that though to make sure there's no issues, as I haven't tested it much and there are quite a few KaTeX variables and some of them look like they might be trouble.

**Comment by dragonwocky** [comment]
@mtoohey31 if you'd like, please open a PR with that css file to the https://github.com/notion-enhancer/tweaks repo (at some point it'll become part of the enhancer's website so users can easily find custom css to add with the custom-inserts).

otherwise i'm closing this issue because unlike the other fonts, which can be set to anything and still work, only certain fonts will work for the math rendering - if a feature is likely to break things for ordinary users, i generally try avoiding adding simple ways to cause problems and leave poweruser features to poweruser-level implementation.

**Comment by dragonwocky** [comment]
@mtoohey31 fira math specifically and loading it externally

**Comment by mtoohey31** [comment]
Sounds good, will do!
