### ISSUE TITLE
notion enhancer not working with latest update

### ISSUE THREAD

**Issue by spencershastings** [notion-enhancer/notion-enhancer#409]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
notion enhancer no longer appears with Notion 2 on mac.

**expected behaviour**
it should install properly and work upon opening notion, but it does neither of those things. i followed the updates page multiple times, I restarted my laptop, I tried everything. Nothing works. 

**screenshots**
Not really applicable, it just won't install properly.

**platform**
macOS

**Comment by dragonwocky** [comment]
are you sure about that? it definitely does work for me and many other users on the current version (2.0.11).

the update guide is only relevant if you are updating from v0.7.0 or lower. did you only try following it, or did you go through the proper [installation instructions](https://github.com/notion-enhancer/notion-enhancer#installation)?

also, the enhancer's individual features mostly aren't turned on by default. you need to go into the menu (click the enhancer's icon on the menubar in the top-right corner on the screen) and turn them on after the enhancer is installed. did you try that?

it sounds like you've done something wrong during installation, please go through the installation and post screenshots of each step in https://discord.gg/sFWPXtA to get help.
