### ISSUE TITLE
HTML Inserts

### ISSUE THREAD

**Issue by spencershastings** [notion-enhancer/notion-enhancer#411]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

ONCE ALL INFORMATION HERE HAS BEEN FILLED IN, THE MODULE WILL BE REVIEWED & DISCUSSED
BY OTHER CONTRIBUTORS AND BY THE COMMUNITY. IF IT IS APPROVED AS SOMETHING USEFUL/BENEFICIAL,
THEN IT IS GUARANTEED TO BE ADDED TO THE ENHANCER.

IF YOU WOULD LIKE TO CONTRIBUTE AND CODE THIS YOURSELF, THAT'D BE AWESOME! JUST OPEN A
PULL REQUEST WHEN YOU'RE READY. IF PROGRAMMING ISN'T YOUR THING, ANOTHER DEV WILL COME
ALONG AND PICK THE IDEA UP.

ONCE SOMEONE STARTS WORK ON THIS, THE ISSUE WILL BE ASSIGNED TO THEIR GITHUB ACCOUNT
SO MULTIPLE PEOPLE DON'T ALL WORK ON THE SAME THING: IF YOU PLAN ON MAKING THIS, SAY SO!

**problem**

why is this feature necessary? how will it help? what existing shortcomings does it address?

I think it is necessary because if you're trying to change styling on certain features, you are unable to override certain ones if Notion styled it using html contenteditable. Adding the option of uploading HTML inserts, you could override the original contenteditable.

**solution**

how will this feature appear/act?

Essentially, it would be added under custom inserts. Right now there's an option for CSS and javascript. A third option, which would allow HTML inserts, would be added.

how could this be technically implemented using the available
capabilities of the enhancer and notion?

You'd be able to upload an html file under custom inserts. 

**cons**

what are the potential costs or dangers of this feature, or things that may go
outside of the enhancer's scope? e.g. bad performance, security issues, or
modifying the data notion stores.

I guess your HTML inserts could screw up Notion's base code.

**alternatives**

would a different feature remove the need for this?

I'm not so sure.

does this need to be implemented by the enhancer? could an external service work better?
e.g. playing background music via noisli or youtube.

I tried overriding the contenteditable via js and css, neither worked.

**Comment by dragonwocky** [comment]
no. "html inserts" is too general. where would the HTML be inserted? and when, since page content is changing all the time?

you can achieve what you want by modifying the dom with javascript, but a HTML insert wouldn't work helpfully.
