### ISSUE TITLE
swipe left/right on the touch pad does not redirect to the desired page (macOS)

### ISSUE THREAD

**Issue by netanelravid** [notion-enhancer/notion-enhancer#415]
**describe the bug**
swipe left/right (back/next page) does not work with mac touch pad

**expected behaviour**
swipe left on touch pad - go to the previous page
swipe right on touch pad - go to the next page

**platform**
macOS

**Comment by dragonwocky** [comment]
does swiping work without the enhancer?

(is this a bug or a feature request?)

**Comment by netanelravid** [comment]
It's a bug, without the enhancer it works.

**Comment by dragonwocky** [comment]
@netanelravid which extensions do you have enabled?

**Comment by netanelravid** [comment]
> @netanelravid which extensions do you have enabled?

- tabs
- tweaks - integrated scrollbars
- tweaks - thicker bold text
- tweaks - hide help button
- tweaks - scroll database toolbars
- bypass preview
- right-to-left
- scroll-to-top

**Comment by dragonwocky** [comment]
@netanelravid if you turn off bypass preview does swiping work?

**Comment by netanelravid** [comment]
> @netanelravid if you turn off bypass preview does swiping work?

no, just turned it off, and still, it is not working

**Comment by netanelravid** [comment]
Is there any new finding/progress regarding this issue?

**Comment by dragonwocky** [comment]
the next enhancer update will feature a complete rewrite. since the cause of this is unknown, it may or may not still be present in that update. closing this issue so i can focus on development of things i can fix. if it still occurs after v0.11.0 is released, please reopen it.
