### ISSUE TITLE
Notion app doesn't open

### ISSUE THREAD

**Issue by dmercado2001** [notion-enhancer/notion-enhancer#417]
**describe the bug** & **screenshots**
the app just doesn't open at all, I get the following error message

<img width="261" alt="Screen Shot 2021-02-09 at 9 02 41 PM" src="https://user-images.githubusercontent.com/77819039/107454001-28a29f00-6b1a-11eb-91e6-7ab1e85d059e.png">
<img width="1440" alt="Screen Shot 2021-02-09 at 9 02 54 PM" src="https://user-images.githubusercontent.com/77819039/107454009-2fc9ad00-6b1a-11eb-8d71-748772a5aa89.png">
<img width="1440" alt="Screen Shot 2021-02-09 at 9 03 05 PM" src="https://user-images.githubusercontent.com/77819039/107454015-36582480-6b1a-11eb-91a5-6e5a950fc99b.png">
<img width="1440" alt="Screen Shot 2021-02-09 at 9 03 13 PM" src="https://user-images.githubusercontent.com/77819039/107454028-3b1cd880-6b1a-11eb-8896-f6459b1402e4.png">

**expected behaviour**
the app should be opening

**platform**
I am using macOS, Big Sur

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/355
