### ISSUE TITLE
Lists and tables without pages

### ISSUE THREAD

**Issue by captainkanpai** [notion-enhancer/notion-enhancer#421]
**The problem**
When using tables or lists, there are a lot of visual distractions. Some tweaks already get rid of for example the title, but I'm still distracted by all the page symbols and underlined entries. 

**The solution**
The ability to make a list or table without each entry to be a new page, or when not possible, to (simply?) hide the symbol and underline of each entry.

<img width="645" alt="Screenshot 2021-02-13 at 10 20 04" src="https://user-images.githubusercontent.com/53567776/107846648-9e8e5b00-6de5-11eb-827b-6085e55888a4.png">
<img width="645" alt="Screenshot 2021-02-13 at 10 20 04 copy" src="https://user-images.githubusercontent.com/53567776/107846651-a0f0b500-6de5-11eb-84ec-7ccc70513157.png">

**Comment by captainkanpai** [comment]
I'm not a programmer, but I like looking at codes, so I tried doing this myself.
By kinda stealing lines from other tweaks, I think I managed to make this code working.
Feels good!
The text is still on the same spot, with an empty space where the symbol was, but I somehow don't mind it and it looks more nicely and compact.
Let me know if the code is how it supposed to be.

/* ========== HIDE SYMBOLS & LINK UNDERLINES IN TABLES ========== */
svg.pageEmpty, .notion-collection_view-block [style="display: flex; align-items: center; margin-right: 6px;"] {
  display: none !important;
}

svg.page, .notion-collection_view-block [style="display: flex; align-items: center; margin-right: 6px;"] {
  display: none !important;
}

div.notranslate, .notion-collection_view-block {
	margin-right: 0px !important;
	border-bottom: 0px !important;
}

**Comment by captainkanpai** [comment]
I managed shifting the text more to the left, think I prefer this for it having more space for text.

div.notranslate, .notion-collection_view-block {
	margin-left: -7px !important;
	border-bottom: 0px !important;
}

**Comment by dragonwocky** [comment]
this is more of a personalised tweak than a feature that would be useful for the majority of users
