### ISSUE TITLE
notion icon has vanished

### ISSUE THREAD

**Issue by caraar12345** [notion-enhancer/notion-enhancer#428]
**describe the bug**
the notion icon has vanished and become a grey square.

**expected behaviour**
there should be an icon!

**screenshots**
<img width="1440" alt="Screenshot of macOS Big Sur dock." src="https://user-images.githubusercontent.com/6129428/108431021-34891200-723a-11eb-84ab-29bfe8acc8e4.png">

**platform**
macos big sur 11.3 beta (20E5172i) 

thank you ❤️

**Comment by dragonwocky** [comment]
That's strange. Did this happen after a while of use or was it triggered by an installation of the enhancer?

**Comment by caraar12345** [comment]
Totally out of the blue! The `electron.icns` file is still in the package which makes it particularly strange. 

I've uploaded my Notion.app file to [Google Drive](https://drive.google.com/file/d/1OlCNFG_TFwjvL8Uyd1Lm0_LSWa-WWX-h/view?usp=sharing) if you wanted to take a look 😄 

I promise there's nothing malicious but feel free to ignore this, open it in a VM or download it on to a computer which you then immediately burn. But just thought you might like to see 😄 

I've now set a custom icon from [macosicons.com](https://macosicons.com) so hopefully that'll stick around - but will see.

**Comment by dragonwocky** [comment]
I don't have a mac to test it on, so if the file is still in the package I have no idea what's happened. ¯\_(ツ)_/¯

Does reinstalling fix?

**Comment by romantech** [comment]
same issue for me. after reinstalling still look vanished icons..

**Comment by romantech** [comment]
> **describe the bug**
> the notion icon has vanished and become a grey square.
> 
> **expected behaviour**
> there should be an icon!
> 
> **screenshots**
> <img alt="Screenshot of macOS Big Sur dock." width="1440" src="https://user-images.githubusercontent.com/6129428/108431021-34891200-723a-11eb-84ab-29bfe8acc8e4.png">
> 
> **platform**
> macos big sur 11.3 beta (20E5172i)
> 
> thank you ❤️

I solved this problem with the method in the [link](https://gist.github.com/fabiofl/5873100#gistcomment-2017545-permalink:~:text=GUYS!%20After%20years%20of%20trying%20the,But%20my%20solution%20works%20every%20time!) below. It's very simple. 
This is a problem with the Mac icon cache.
