### ISSUE TITLE
Emojis not fully downloading/showing up

### ISSUE THREAD

**Issue by quietmansoath** [notion-enhancer/notion-enhancer#429]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
When selecting the HTC and Firefox emoji sets, not all emojis are showing up. Many options are just blank boxes. Persists even after re-initializing. (This may be happening with the other sets, but I haven't tried them).

**expected behaviour**
I was expecting all of the emojis to show up and work with any missing.

**screenshots**
![Screenshot-20210221182451-506x392](https://user-images.githubusercontent.com/46270221/108642324-7d2b1000-7472-11eb-9eef-591e92930a78.png)

**platform**
Pop! OS 20.10 (ubuntu)

**Comment by dragonwocky** [comment]
do the same emojis or different ones disappear when you try different sets? most of the sets aren't actually complete/consistent with each other, which is why notion chooses the twitter set by default - it's likely the emojis are blank because they don't exist.

**Comment by quietmansoath** [comment]
I can see all of mine before I installed the emoji sets "plugin," but there are gaps otherwise. The Facebook and LG icons have different gaps.

**Comment by dragonwocky** [comment]
yep, this is a problem with the individual sets missing emojis. there's nothing i can do about that.
