### ISSUE TITLE
Can't open notion with notion-enhancer.

### ISSUE THREAD

**Issue by KelvinRCao** [notion-enhancer/notion-enhancer#434]
**describe the bug**
After I turn on enhancements 'tabs' and 'default url' and relaunch, the notion-enhancer icon in state bar appears but the windows of notion doesn't appear. 
I have tried re-install notion-enhancer, but it doesn't work. I have also tried to download the code from github and test, which I get the same result.
After I removed notion-enhancer, notion can be opened.

**platform**
Windows 10

**Comment by shaderein** [comment]
I encountered the exact same error today after changing the shortcut to switch between tabs and relaunching the app. It seems like the app is still running in the background when you look at Task Manager. (Windows 10)

**Comment by Zeeennnyyy** [comment]
exact same thing, toggled on font changer and then reset, now the app is impossible to launch with notion enhancer, but i can uninstall it and works fine.

**Comment by dragonwocky** [comment]
dup of #437 - see discord announcements, notion's update has broken the enhancer.
