### ISSUE TITLE
Notion Enhancer not working with latest version, 2.0.14

### ISSUE THREAD

**Issue by shamika69** [notion-enhancer/notion-enhancer#438]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Attempting to download enhancer but once complete, Notion doesnt open at all and essentially breaks.

**expected behaviour**
code runs and notions opens as expected

**platform**
Windows 10

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/437 (so close, bot, so close)
