### ISSUE TITLE
Unusable for Notion v2.0.14

### ISSUE THREAD

**Issue by Theguyhere0** [notion-enhancer/notion-enhancer#440]
**describe the bug**
Upon relaunching from a working version, Notion automatically updates and the notion-enhancer is turned off. When I try to reinstall notion-enhancer through various cycles of uninstalling both this and the actual notion program with restarts, the program doesn't seem to want to work with this module installed.

The main issue is that when I install this module and I try to open Notion, it no longer opens. There is an icon in the task tray, but I can't interact with it.

**expected behaviour**
The program should work with the enhancer.

**screenshots**
Here's a video of me opening up Notion without the enhancement and with the enhancement.

https://user-images.githubusercontent.com/52550799/110249688-2cb0b980-7f2c-11eb-9403-f8306564223d.mp4

**platform**
Windows 10

**Comment by Tripp3235** [comment]
Having same problem and I'm on a Mac.  Tried reinstalling the Enhancer.  Tried installing older version of Notion.  Notion updates and enhancer no longer works.

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/437
