### ISSUE TITLE
Notion Window won't open

### ISSUE THREAD

**Issue by dioneottten** [notion-enhancer/notion-enhancer#441]
**describe the bug**
app is opening but no windows show up, cant click on enhancer tool or use cmd+e either.

**expected behaviour**
a window to use notion should show up

**platform**
macOS Big Sur

**Comment by dragonwocky** [comment]
does the solution in https://github.com/notion-enhancer/notion-enhancer/issues/437 fix this?

**Comment by ayush729p** [comment]
> does the solution in #437 fix this?

@dragonwocky yes.... can confirm this fix works on desktop windows app v2.0.15 too!
