### ISSUE TITLE
Broken with Notion Update - Hack doesn't work

### ISSUE THREAD

**Issue by wahoo2** [notion-enhancer/notion-enhancer#443]
Same issues as everyone else, but after completing the hack, nothing changes.

**Comment by dragonwocky** [comment]
need more information to fix. please provide exact steps you performed and any error/crash logs that might exist.

**Comment by FayaadAbrahams** [comment]
Where is notion enhancer located? I would like to remove since the hack is no longer working

**Comment by dragonwocky** [comment]
@FayaadAbrahams use https://www.youtube.com/watch?v=vcwUpwpQ2sY&feature=youtu.be to fix the hack to work with the latest Notion. Otherwise you can uninstall by running `npm remove -g notion-enhancer` in cmd/terminal or reinstalling Notion.

**Comment by FayaadAbrahams** [comment]
Thanks for that

**Comment by wahoo2** [comment]
I followed the steps exactly. I am on a Mac, however, so is it possible the files are not located where I think they are (I used the files that were unzipped in my downloads folder)?

**Comment by dragonwocky** [comment]
@wahoo2 yeah, no. Simply downloading and unzipping the files doesn't link them to Notion. Please follow the instructions *very carefully* (use the video and the link at the top of the instructions if you need). The files already exist on your system without you downloading anything. The instructions do include information on how to find them.
