### ISSUE TITLE
Notion Icons not drawn or missing

### ISSUE THREAD

**Issue by jwhiteHoney** [notion-enhancer/notion-enhancer#444]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
With Enhancement installed and running, the Notion App Icon and Icons visible in the Tabs, appear to go missing after a few days. 
**expected behavior**
Icons in the tabs and App appear like other apps
**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/70538370/111219004-bf88ce00-8594-11eb-9208-0cb7f0ef6f51.png)
![image](https://user-images.githubusercontent.com/70538370/111219161-ee9f3f80-8594-11eb-8a53-4401fcc4b834.png)

**platform**
Mac Book Pro
OSx Catalina (its terrible, keep ignoring those updates folks)
![image](https://user-images.githubusercontent.com/70538370/111219309-155d7600-8595-11eb-9460-9e72b2eba991.png)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/428 / https://github.com/notion-enhancer/notion-enhancer/issues/365 / https://github.com/notion-enhancer/notion-enhancer/issues/370
