### ISSUE TITLE
Can't open others' shared pages in enhancer

### ISSUE THREAD

**Issue by OptimusPrimeme** [notion-enhancer/notion-enhancer#445]
**describe the bug**
I can't open others' shared page.
**expected behaviour**
I  copy others' page link to my workspace.But I can't open it in enhancer. 
**screenshots**
![image](https://user-images.githubusercontent.com/22427706/111272365-7eb0b800-866d-11eb-94de-7117fb944361.png)

**platform**
windows 10

**Comment by dragonwocky** [comment]
@OptimusPrimeme does closing this mean that it's working? Sorry I haven't replied yet, been too busy recently to pay too much attention to the enhancer.
