### ISSUE TITLE
I can't find this path notion-enhancer/mods/core/ on my Mac

### ISSUE THREAD

**Issue by almajbary** [notion-enhancer/notion-enhancer#447]
Greetings everyone,

I am trying to find the path notion-enhancer/mods/core/ to fix the compatibility issues with the new version of Notion.

kindly, any idea how to find it?

thank you.

**Comment by chee** [comment]
if you have `notion-enhancer` in your PATH, you could try something like this:

```bash
realpath `which notion-enhancer`
```

which should print something like `/usr/lib/node_modules/notion-enhancer/bin.js`

in my example, i can use that prefix to find `mods/core` at:

`/usr/lib/node_modules/notion-enhancer/mods/core`

**Comment by almajbary** [comment]
Thank you very much 🙏🏻 everything works perfectly now 😊
