### ISSUE TITLE
Theme's not workng?

### ISSUE THREAD

**Issue by dinjngo** [notion-enhancer/notion-enhancer#448]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
Installed enhancer but themes don't seem to be working
**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.`
<img width="387" alt="Screen Shot 2021-03-17 at 3 13 21 PM" src="https://user-images.githubusercontent.com/80852478/111525425-ffd28280-8733-11eb-9a1b-9997db6474e0.png">

<img width="1392" alt="Screen Shot 2021-03-17 at 3 13 02 PM" src="https://user-images.githubusercontent.com/80852478/111525406-f77a4780-8733-11eb-99e9-c7cfe63aeb0f.png">
**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
macOS

**Comment by chee** [comment]
the theme you've chosen is a dark theme (see `#dark` in its tags), so you need to go into your Notion settings, choose Appearance and set theme to Dark
