### ISSUE TITLE
Completely missing

### ISSUE THREAD

**Issue by lbspen** [notion-enhancer/notion-enhancer#451]
**describe the bug**
Today I just installed notion-enhancer and there is no change in notion. I have a Mac running Catalina. I uninstalled and reinstalled notion, so I have the very latest version, 2.0.16. notion-enhancer is 0.10.2. When I run `notion-enhancer check` it says `notion-enhancer v0.10.2 applied.` When I first installed, I experienced the notion would not open problem. I followed the hack instructions and now notion opens. However, the icon in the dock doesn't have anything related to notion-enhancer.

**expected behaviour**
From the pictures in the README, it looks like you interact with notion-enhancer through the icon in the dock. I would expect to see something there, or in the notion preferences, or some menu somewhere.

**screenshots**
if applicable, add screenshots of your problem.

![image](https://user-images.githubusercontent.com/1879795/111919401-0f5d0e80-8a47-11eb-80a4-cc33a4f7331b.png)

**platform**
macOS catalina

**Comment by joshdavies14** [comment]
If the enhancer has applied correctly you should have a Notion icon in the top right of your screen (in the menu bar near your time, battery etc.) which provides the interaction with the enhancer, not the dock icon. The screenshots in the README are taken on Windows and the location of the enhancer icon is different between Windows and Mac -> on Windows the dock and menu bar icons are combined in the taskbar. Hope that helps!

**Comment by lbspen** [comment]
Thanks for your reply - unfortunately I don't see anything there either

![image](https://user-images.githubusercontent.com/1879795/111921100-f73dbd00-8a4f-11eb-9df3-ba35475b6857.png)

**Comment by SatoriDevil** [comment]
I've been experiencing a similar problem with notion not opening up in enhancer, even though it's been installed, it just opens normally

**Comment by dragonwocky** [comment]
@SatoriDevil there is no such thing as "notion opening up in enhancer". the enhancer adds stuff to notion but isn't super noticeable unless you go into the menu and turn stuff on/off.

not sure what's happening if it says it's installed though and the enhancer icon in the tray/menu doesn't exist.

**Comment by dreamfordearest** [comment]
I also have this error. I applied the fix that @dragonwocky uploaded at the comment section of #437 to open my notion desktop app with enhancer, but the enhancer icon in the tray disappeared right after that with no enhancements applied. I'm a windows 10 user.

**Comment by nilsoskar** [comment]
I have the same issue and also reinstalled and followed the instructions. How did you resolve it? Did you do anything differently the last time?

**Comment by lbspen** [comment]
In the instructions there are two modifications to files. One of them is an addition to an existing line, and the other one is a new line of code. The most recent time I reinstalled, at first I didn't add the second snippet because I thought it was supposed to be appended to a line of code, but the instructions stated line 19, which is blank. After that didn't work, I put the new code in at the blank line. It worked!

**Comment by nilsoskar** [comment]
Thanks for the update! Unfortunately still not working for me though
