### ISSUE TITLE
Text Cursor is GONE

### ISSUE THREAD

**Issue by MagedtheDragon** [notion-enhancer/notion-enhancer#456]
[The Disappearance of the Text Cursor.pdf](https://github.com/notion-enhancer/notion-enhancer/files/6216881/The.Disappearance.of.the.Text.Cursor.pdf)

**Comment by reVoniaC** [comment]
I encountered the same problem too. But I've discovered that clicking on a non-Notion window (e.g. File Explorer, Chrome, whatever) then clicking on the Notion window again brings the cursor back up.
It's still a bug that needs fixing though.

**Comment by iamlinkent** [comment]
[bug](https://github.com/notion-enhancer/notion-enhancer/issues/400)

**Comment by agnashetty** [comment]
Go to settings -> Accessibility -> Mouse pointer & touch. Then change the mouse pointer style to Dark. that should fix the issue
