### ISSUE TITLE
`notion-enhanced` updates `~/.config/mimeapps.list` unnecessarily.

### ISSUE THREAD

**Issue by trustin** [notion-enhancer/notion-enhancer#457]
**describe the bug**

I'm currently using `notion-enhanced` installed from your apt repository in Ubuntu 20.04 LTS. Whenever I launch `notion-enhanced` by clicking the launcher from GNOME desktop, it updates or adds the following line in my `~/.config/mimeapps.list` file:

```
text/html=notion-enhanced.desktop
```

I explicitly associate my web browser with `text/html` (e.g. `text/html=x-www-browser.desktop`), but it keeps getting reverted by `notion-enhanced` whenever it launches.

**expected behaviour**

`notion-enhanced` should never touch my `mimeapps.list` file.

**platform**

Ubuntu 20.04.2 LTS

**enabled enhancements**

- notion-enhancer code
  - auto-maximise windows
- tweaks
  - integrated scrollbars
  - thicker bold text
  - scroll database toolbars
- indentation lines
  - style: soft
  - bulleted list
  - numbered list
  - to-do list
  - toggle list

**Comment by dragonwocky** [comment]
hi, issues related to the notion-enhanced linux package should be made to https://github.com/davidbailey00/notion-linux. the enhancer here can be added to the notion app on any platform, while the notion-enhanced is a 3rd-party package that contains both notion & the enhancer. (also, the enhancer alone does not modify mimeapps.)

**Comment by trustin** [comment]
Thanks for the point, @dragonwocky. Created an issue there - https://github.com/davidbailey00/notion-linux/issues/42
