### ISSUE TITLE
Can't open notion after apply

### ISSUE THREAD

**Issue by Xwil** [notion-enhancer/notion-enhancer#459]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
After run `notion-enhancer apply`,  and result is success.
No window opend after open notion, can't open notion.

**expected behaviour**
Open window when open notion

**screenshots**
No screenshot needed

**platform**
macOS Big Sur, version 11.1
notion 2.017

**Comment by Xwil** [comment]
I've tried #437 solution, didn't work.

**Comment by imyu37** [comment]
> 
> 
> I've tried #437 solution, didn't work.

I found the same problem, and the solution of # 437 works for me.
