### ISSUE TITLE
Themes Not Applying Fully

### ISSUE THREAD

**Issue by ydnaroday** [notion-enhancer/notion-enhancer#461]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
When activating a theme, the main notion application is not changed. Only the notion-enhancer extension window is changed. 

**expected behaviour**
The theme should apply to the whole application.

**screenshots**
<img width="1440" alt="Screen Shot 2021-04-11 at 8 00 33 AM" src="https://user-images.githubusercontent.com/15266826/114305061-1a321e80-9a9c-11eb-8610-9e8b003386d4.png">

**platform**
I am on macOS, Big Sur. Intel processor if that helps.

**Comment by dragonwocky** [comment]
is this https://github.com/notion-enhancer/notion-enhancer/issues/291#issuecomment-742237034?

**Comment by ydnaroday** [comment]
Yup, that is the issue. I can see a bunch of content policy issues in the dev menu. 

I will try messing around with my network settings. Thanks!
