### ISSUE TITLE
smaller minimum column width tweak?

### ISSUE THREAD

**Issue by GitMoleo** [notion-enhancer/notion-enhancer#463]
**problem**

I want to waste as less space as possible (especially in timeline views) so the minimum width for columns is to big some times.

**solution**

A extension to overwrite the minimum column width and set it to a custom value.

**cons**
-

**alternatives**
-

**Comment by dragonwocky** [comment]
try https://github.com/notion-enhancer/tweaks/blob/main/tweaks/table%20columns%20below%20100px.md

**Comment by GitMoleo** [comment]
I did everything as mentioned in the video, but how do I actually apply the `custom_style.css` file to notion?

**Comment by dragonwocky** [comment]
@GitMoleo use the file picker under the custom inserts extension in the enhancer menu.

**Comment by focalhaus** [comment]
I had to remove some of the styling attributes in the CSS selectors to make it work. FYI. And thanks a million for your contributions.
