### ISSUE TITLE
Unable to open notion-enhancer GUI [Alt + E]

### ISSUE THREAD

**Issue by goliakshay357** [notion-enhancer/notion-enhancer#469]
I'm unable to open the notion-enhancer GUI when [Alt+E] is pressed though notion-enhancer is enabled.
![image](https://user-images.githubusercontent.com/32712438/115996882-af85f480-a5fe-11eb-877c-0e5f59e60cf3.png)

OS Details:
![image](https://user-images.githubusercontent.com/32712438/115996899-be6ca700-a5fe-11eb-92a0-4961fc4cc2d5.png)

Installed notion-linux via https://github.com/jaredallard/notion-app

**Comment by aravindveluri** [comment]
Facing same issue on popOS  20.04

**Comment by NickHatBoecker** [comment]
Same problem on MacOS Catalina. With the patched version and the repackaged one

**Comment by dragonwocky** [comment]
try opening it via the menubar/tray icon. the hotkey bug is known and a fix will be part of the next update
