### ISSUE TITLE
Notion app not opening

### ISSUE THREAD

**Issue by Rij29** [notion-enhancer/notion-enhancer#471]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
My notion app was working fine before I installed notion-enhancer. Now, everytime I try to open my notion app, the icon shows up in the dock but there is no visible window of the app. The app should show the window as well as have the notion-enhancer option along with it. Please help!

**platform**
I am using macOS Big Sur

**Comment by dragonwocky** [comment]
https://www.notion.so/dragonwocky/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

**Comment by alaa-os** [comment]
I have the same problem. I followed all the steps but still, the app won't open the icon appear on the dock and I can see the notion enhancer icon but the app won't open
