### ISSUE TITLE
Notion doesn't open after installation

### ISSUE THREAD

**Issue by Biszkoptu** [notion-enhancer/notion-enhancer#472]
After installation and apply, Notion doesn't open

Windows 10

![image](https://user-images.githubusercontent.com/55443033/116072342-3d112500-a68f-11eb-878f-8ba19d6a6b58.png)
![image](https://user-images.githubusercontent.com/55443033/116072388-4ac6aa80-a68f-11eb-8959-e84ca725b34d.png)

**Comment by GitMoleo** [comment]
Try this: https://github.com/notion-enhancer/notion-enhancer/issues/437#issuecomment-787436709
