### ISSUE TITLE
安装notion-enhancer之后，出现了A JavaScript error occurred in the main process 

### ISSUE THREAD

**Issue by ShigaHaruki** [notion-enhancer/notion-enhancer#475]
![RTMFC8ZXLO ($HW9J)E7XAF](https://user-images.githubusercontent.com/68691294/116505122-b194cf80-a8ec-11eb-9b57-6c485c3e136f.jpg)
我安装完notion-enhancer以后出现了这种错误
我不清楚是什么情况
希望可以得到解决

**Comment by ShigaHaruki** [comment]
我也进行了修复https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041

**Comment by dragonwocky** [comment]
never seen that error before, but from the information it provides I can't link it with a specific part of the enhancer, so I can't fix it.
my best bet would be try reinstalling notion and see if that helps.
