### ISSUE TITLE
Can't Apply the Enhancer>>  Installation has been corrupted: no executable found. 

### ISSUE THREAD

**Issue by YahiaJr** [notion-enhancer/notion-enhancer#476]
I'm on Arch Linux... After applying the fix mintioned [Here](https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041), and Trying to apply the enhancer from the terminal using the `notion-enhancer apply -y` command, an error occures reporting the following:

=== NOTION ENHANCEMENT LOG ===
### ERROR ###
Error: notion installation has been corrupted: no executable found.
    at module.exports (/usr/lib/node_modules/notion-enhancer/pkg/apply.js:31:15)
    at async CAC.<anonymous> (/usr/lib/node_modules/notion-enhancer/bin.js:30:5)
=== END OF LOG ===

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/467, there are some incompatibilities with the latest aur version. you could try installing an older version or one of the messages in that thread has some details to manually get things working.
