### ISSUE TITLE
 You do not have permission to open the application “Notion”.

### ISSUE THREAD

**Issue by Rij29** [notion-enhancer/notion-enhancer#479]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Anytime my machine restarts and I try to open Notion I get the error message: You do not have permission to open the application “Notion”.

**platform**
macOS Big Sur

**Comment by dragonwocky** [comment]
did you run `codesign --force --deep --sign - /Applications/Notion.app`?

**Comment by Rij29** [comment]
No, I didn't

**Comment by dragonwocky** [comment]
yes. it will. please read the installation instructions properly. that's in them.
