### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by Rij29** [notion-enhancer/notion-enhancer#480]
**describe the bug**
I have applied the neutral dark theme, but it doesn't seem to work for some reason. 

**screenshots**
<img width="1314" alt="Screenshot 2021-05-05 at 7 25 38 PM" src="https://user-images.githubusercontent.com/71190505/117155676-989f8900-adda-11eb-97fe-47b0a6ab9623.png">

**platform**
macOS Big Sur

**Comment by dragonwocky** [comment]
please open the console with Option + ⌘ + J and provide a screenshot

**Comment by Rij29** [comment]
I have attached a screenshot with the post...

**Comment by dragonwocky** [comment]
> please open the console with Option + ⌘ + J

a screenshot of the console

**Comment by Rij29** [comment]
The console of the browser?

**Comment by dragonwocky** [comment]
notion's console (the notion app is basically a modified and simplified browser)

**Comment by Rij29** [comment]
True and I tried opening the console using option + cmd + J, but it didn't open

**Comment by nammminn2** [comment]
having the same issue as well was trying dark + but I dont see no change except in the Alt+E settings

**Comment by dragonwocky** [comment]
see #291 - it's an unpredictable network/app security caused error where the enhancer's styling gets blocked. until a fix is released in the next update, you could try restarting the app a few times or switching networks, as that sometimes solves it.
