### ISSUE TITLE
Mac: Notion won't open

### ISSUE THREAD

**Issue by zakiaziz** [notion-enhancer/notion-enhancer#481]
**describe the bug**
After running `notion-enhancer apply` Notion won't open. There is an icon in the menubar which wasn't there before but the actual app window does not show.

**expected behaviour**
Notion should open with the enhancements applied

**screenshots**
N/A

**platform**
MacOS 11.3 (M1 Macbook Air)

**Comment by dragonwocky** [comment]
https://www.notion.so/dragonwocky/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041
