### ISSUE TITLE
JS Error when launching Notion

### ISSUE THREAD

**Issue by emilianovb** [notion-enhancer/notion-enhancer#482]
I get this error when launching Notion. I have uninstalled and re-installed Notion, the enhancer, and node.js several times. I downloaded all files and followed all installation steps correctly. Using the latest versions of Notion, Notion Enhancer, and Node.js.

**screenshots**
![image](https://user-images.githubusercontent.com/66089450/117382010-520d6580-ae92-11eb-8a2f-5dccfceb98bd.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-enhancer/issues/474
