### ISSUE TITLE
Notioin is not working on windows 10.

### ISSUE THREAD

**Issue by bishwaadhiarki** [notion-enhancer/notion-enhancer#485]
The Notion app on windows 10 is not working well. With a double click, the app opens but can't load anything is stocked just on a white screen. 
I have tried everything from uninstalling to removing all the temp files of the app. 
![one B ](https://user-images.githubusercontent.com/30983598/117795009-7d66ca80-b26d-11eb-9bef-0808f4df3814.jpg)

**Comment by DarkFlamex1** [comment]
Have you followed the link in the readme? https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041 
I had the same problem but it turns out I just had to follow these steps!

**Comment by bishwaadhiarki** [comment]
now I can see the notion enhancer is working properly but the notion app is just blank out, I can't see anything except the white screen. 
What should I do? Am I the only one who is facing the problem on the whole internet.  I don't need the enhancer thing I just want the pure notion app which is not working here, I have installed and uninstall it several times.

**Comment by dragonwocky** [comment]
if you followed the steps fully the enhancer should be working properly.
if you've reinstalled notion cleanly without the enhancer and the notion app still isn't working then it's a problem with your notion, unrelated to here and something I can't help you fix.
