### ISSUE TITLE
After hiding dragarea, how to drag other places to move the window?

### ISSUE THREAD

**Issue by plain-dev** [notion-enhancer/notion-enhancer#486]
**problem**

After hiding dragarea, how to drag other places to move the window?

**solution**

**cons**

**alternatives**

**Comment by plain-dev** [comment]
Setting item found `height of frameless dragarea`

When the setting value is `0`, ***dragarea*** is hidden. Is there any way to drag other areas to move the window at this time?

**Comment by dragonwocky** [comment]
no. the dragarea is how you move the window. if you remove the dragarea, you cannot drag the window. it's that simple.
