### ISSUE TITLE
Errors with macOS 10.15.7

### ISSUE THREAD

**Issue by GentleCP** [notion-enhancer/notion-enhancer#489]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Hi, I found a few errors when I use notion-enhancer on my macbook. The version I used for notion is 2.0.17(latest for now on offical website)
1. icon display error
Well, when I followed the steps in https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041 and I tried to turn some options on like `scroll to top`, `words counter` and I got things like this:
![image](https://user-images.githubusercontent.com/38175267/118351911-23c60f00-b591-11eb-824d-be40806726dd.png)
![image](https://user-images.githubusercontent.com/38175267/118351934-3d675680-b591-11eb-84a0-d7c1861acf3b.png)
2. Theme did not work
When I chose a theme like `littlepig light`, it did not show the theme which I expected. 
3. Others
Absolutely, I also tried other options, such as `outliner` while it did not work either.

I'm really sure that I had followed all the steps that previous issues had suggested and reinstall notion and notion-enhancer for many times. However, nothing changed.
![image](https://user-images.githubusercontent.com/38175267/118352129-58869600-b592-11eb-84bb-d2b1a232dd53.png)
![image](https://user-images.githubusercontent.com/38175267/118352121-4dcc0100-b592-11eb-8a42-ecdf8b750818.png)

Really appeciate it if you could help me fix this problem.

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
see description. 
**platform**
macOS

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/291 - it's an unpredictable network/app security caused error where the enhancer's styling gets blocked. until a fix is released in the next update, you could try restarting the app a few times or switching networks, as that sometimes solves it.

**Comment by GentleCP** [comment]
I've tried restarting the app(even reset app and clear local data) and switch networks, sadly, nothing changed, finally I gave up. Anyway, thanks a lot, hope the next release could be published sooner.

**Comment by wujunchuan** [comment]
Same to me, I think it not network
