### ISSUE TITLE
Not showing window control buttons

### ISSUE THREAD

**Issue by ddiegosr** [notion-enhancer/notion-enhancer#491]
**describe the bug**
The buttons to control the window(minimize, maximize, close) are not showing.

**expected behaviour**
Should show the buttons to maximize, minimize and close the window.

**screenshots**
![image](https://user-images.githubusercontent.com/5925920/118565272-43536800-b748-11eb-9524-c643cbf3533e.png)

**platform**
Linux(Pop-OS 20.10)

**Comment by PenguinxEnjoi** [comment]
Same for me

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/291
