### ISSUE TITLE
(Mac) Can't install Notion Enhancer

### ISSUE THREAD

**Issue by thesilenthunt** [notion-enhancer/notion-enhancer#494]
Trying to install notion enhancer on my Mac (Catalina 10.15.7) but it doesn't work. I followed the instructions at least 10+ times. Uninstalling notion enhancer in terminal each time to try and start anew but to no avail. What happens after I complete the instructions is that: 1. Notion won't open (blank) 2. Notion is forced to quit. 

I then realized there are some issues making Notion Enhancer compatible with the newer versions of Notion so I followed [those](https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041) instructions as well. 

I'm having difficulty following those instructions however as the video provided is on a windows computer and I am having trouble finding the right folders to open in order to make the changes. 

Can someone help me to find the correct filepath to access the AppData/Roaming/npm...etc. so I can try to make the changes so I can have Notion Enhancer work? 

Really trying to make this work as I'm really interested in the program and it looks awesome but I just can't get over the limited type faces (I'm a designer) provided and I honestly don't see why you aren't able to make the look and feel of the program more custom to your personal preferences if it's supposed to be a type of second mind. 

Any help would be greatly appreciated.

**Comment by dragonwocky** [comment]
the folder you need is probably `/usr/local/lib/node_modules/notion-enhancer`

**Comment by thesilenthunt** [comment]
yes sir that worked! thank you so much

**Comment by thesilenthunt** [comment]
do you have instructions on using your own custom fonts? I was searching for some info online and they all are using googlefonts somehow but I was wondering if there was a way for me to import my own font files to use?

It already all looks much better with the all black theme but if I could use my own fonts that would just make me want to use the program all the more. 

thanks again.
