### ISSUE TITLE
Notion-enhancer not open, Notion(2.0.16)

### ISSUE THREAD

**Issue by mekpower** [notion-enhancer/notion-enhancer#495]
Hello! Anyone can help me? For me keep dot working, my notion works fine, but the notion-enhancer dont appear. The icon in taskbar dont show, in task manager dont appear nothing. I used the commands `notion-enhancer apply` and `notion-enhancer check` and it say that is applied. I already did the steps of #437  and it still doesn't work. 

I don't know if this brings any problems, but my notion is on another HD, connected to C: disk with mklink. Before updating the notion, the notion-enhancer worked normal. 

**platform**
windows 10

_Originally posted by @mekpower in https://github.com/notion-enhancer/notion-enhancer/issues/437#issuecomment-841485434_

**Comment by dragonwocky** [comment]
You might be right with the HD problem... can you test, if you install Notion normally instead does the enhancer work?

**Comment by mekpower** [comment]
Its worked for me, but have a way to redirect notion-enhancer to other driver or to recognize the mklink? Because my C: drive is a SSD with low space.

**Comment by dragonwocky** [comment]
when installing the enhancer it will need to be on C:, but afterwards you should be able to copy/paste the `C:\Users\Name\AppData\Local\Programs\Notion\resources\app` to the corresponding resources folder on the other drive and that should work.

**Comment by mekpower** [comment]
Thanks @dragonwocky for all!
