### ISSUE TITLE
Texts written in the quote are out of the search scope.

### ISSUE THREAD

**Issue by kmn** [notion-enhancer/notion-enhancer#502]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Texts written in the quote at the Table - Board view could not be found even when the texts are inputted in the search form.

**expected behaviour**
I excpected texts written in the quote are within the search scope.

**screenshots**

**platform**
MacOS Big Sur v11.3.1（20E241）

**Comment by dragonwocky** [comment]
do you mean notion's quick find? or the ctrl+f? either way, the first is handled internally by notion and the second by the browser/app itself. that's not something the enhancer can affect.

**Comment by kmn** [comment]
Sorry, I missed a pic attached.
I meant this search box below.
<img width="1198" alt="スクリーンショット 2021-06-04 2 03 46" src="https://user-images.githubusercontent.com/973161/120808661-db8c8200-c57b-11eb-9124-d6bea82269bf.png">

**Comment by kmn** [comment]
Even the texts exist inside the quote area, the search result remains same.
<img width="956" alt="スクリーンショット 2021-06-04 2 04 40" src="https://user-images.githubusercontent.com/973161/120809235-71281180-c57c-11eb-9ec4-d7668edd0e7f.png">

**Comment by dragonwocky** [comment]
still, that's part of notion's search algorithm. i can't fix that, unfortunately + I'm pretty sure that search box is only meant to search page titles & properties, not content.
