### ISSUE TITLE
Weird loading in with some enhancements after reinstalling?

### ISSUE THREAD

**Issue by milao11** [notion-enhancer/notion-enhancer#503]
Using Win10 and had notion enhancer for a while but after running into some problems with the font-chooser I got annoyed and decided to reinstall the entire thing again, now everything is wonky especially with the icons. Almost everything seems to be not working like the bracketed links, the tweaks, the outline section is just dominated with the arrow top button, and I have no idea what those large question marks are.

The themes still seem to work fine tho, the major letdown would still be the font-chooser not working sadly lol. I already also went the extra mile with deleting old files in appdata and deleting Notion itself, barely did anything :(

![Screenshot (781)](https://user-images.githubusercontent.com/85168373/120919356-bf0f5780-c6eb-11eb-8030-7a6aacf763fd.png)
![Screenshot (782)](https://user-images.githubusercontent.com/85168373/120919357-c0408480-c6eb-11eb-8140-3fbff3fa52b0.png)
![Screenshot (783)](https://user-images.githubusercontent.com/85168373/120919358-c0d91b00-c6eb-11eb-8396-17a143ff44e0.png)

**Comment by bvoo** [comment]
I'm having the same issues. Not sure what's causing it, after I followed the steps for the hack to work with 2.0.13+.

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/291 for explanation and potential solutions
