### ISSUE TITLE
There are huge close/maximize/minimize buttons

### ISSUE THREAD

**Issue by pomaa666** [notion-enhancer/notion-enhancer#511]
**describe the bug**
The close, maximize and minimize buttons are huge, it did not look like this in the demo pictures. This happened after I followed the steps on the fix video, otherwise it just did not open.

**expected behaviour**
The buttons should look like in any other app

**screenshots**
![image](https://user-images.githubusercontent.com/86126344/122603024-098dbe00-d074-11eb-8f6a-c274f42ad78b.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/291
