### ISSUE TITLE
Notion App not opening after installing notion-enhancer

### ISSUE THREAD

**Issue by Akash-Sharma-1** [notion-enhancer/notion-enhancer#515]
**describe the bug**
After installing the notion enhancer through the npm command - the notion app doesn't open at all

**expected behaviour**
After installing, I checked in the cmd using the `notion-enhancer check` option - It says notion-enhance is applied. The notion enhancer app icon does come up in the task tray but right or left-clicking has no effect. Notion desktop app is also not opening. However, I can see the notion-enhancer process in the task manager. 

When I remove the notion enhancer package, normal notion app now opens when clicked

**screenshots**
![Installing the package](https://user-images.githubusercontent.com/33986563/122772370-edcd2680-d2c4-11eb-8e62-9243d7cde92d.png)
![Notion enhancer process is working](https://user-images.githubusercontent.com/33986563/122772537-1ce39800-d2c5-11eb-8bfd-a588a57cad0b.png)
![Few notion processes are working as well](https://user-images.githubusercontent.com/33986563/122772842-692ed800-d2c5-11eb-903c-662377631af6.png)

**platform**
- Windows 10 
- Notion Version - 2.0.16

**Comment by jhchabran** [comment]
Had the same issue, https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041 fixed it (the README mentions it).

**Comment by Akash-Sharma-1** [comment]
Thank you very much for your help @jhchabran!
I missed this in the README.

My sincere apologies for creating a duplicate issue.
