### ISSUE TITLE
Notion AI My mind on macOS Big sur

### ISSUE THREAD

**Issue by suryaatevellore** [notion-enhancer/notion-enhancer#521]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
python3 server.py reports this error 
```
*** socket.gaierror: [Errno 8] nodename nor servname provided, or not known```

**expected behaviour**
This shouldn't have happened in the first place 

**screenshots**
if applicable, add screenshots of your problem.

**platform**
macOS

**Comment by suryaatevellore** [comment]
This issue was resolved by taking the following steps, and running the commands in your chosen console ($ is your PS prompt)
1. Own the /etc/hosts file if you are unable to edit it 
```
$ chmod 777 /etc/hosts
```
2. Add the entry for resolving the local IP 127.0.0.1 to your hostname in /etc/hosts
```
echo 127.0.0.1 $(hostname) >> 127.0.0.1
```

**Comment by dragonwocky** [comment]
...what does this have to do with the enhancer?
