### ISSUE TITLE
enhancments not working and right tab too big

### ISSUE THREAD

**Issue by lidoror** [notion-enhancer/notion-enhancer#525]
![image](https://user-images.githubusercontent.com/86961985/124465179-c3d43380-dd9d-11eb-9de5-fa6ed4b6bf72.png)
this is the exit , expand and minimize icon and when I am enabling the RTL enhancement nothing happened.

**Comment by Kumbhira** [comment]
Maybe works
1. Reinstall notion v2.0.12 and enhancer, then update to v2.0.16.
2. Following the [steps](https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041) to fix notion.

**Comment by adityacryptota** [comment]
You need to go to: 
C:\Users\username\AppData\Roaming\npm\node_modules\notion-enhancer\mods\core

In the file **client.js**, go to around line number 122 and comment out this piece of code:
`if (!tabsEnabled) {
      const buttons = require('./buttons.js')(store);
      document
        .querySelector('.notion-topbar > div[style*="display: flex"]')
        .appendChild(buttons.element);
    }`

Then restart notion.

**Comment by dragonwocky** [comment]
see #291
