### ISSUE TITLE
Theme option does not work with 2.0.16 notion

### ISSUE THREAD

**Issue by liuyang2356** [notion-enhancer/notion-enhancer#528]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
After installing notion-enhancer and following the instructions here https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041 
I was able to launch notion and notion enhancer in the app. 
But when I toggle on the dracula theme and then click on the refresh app. The app relaunches but the theme didn't change at all. 
**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
mac

**Comment by dcmba** [comment]
![Screenshot 2021-07-21 094222](https://user-images.githubusercontent.com/76493250/126526831-3ebe08a2-2232-4189-b1cc-48c9ed0f6b58.png)
Same issue here. I"m using #Dark theme but clearly you can see it's not working. I'm running on Windows 10

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/291
