### ISSUE TITLE
notion enhancer icon not showing up on menu bar even after using hack

### ISSUE THREAD

**Issue by amensk** [notion-enhancer/notion-enhancer#533]
notion enhancer icon not showing up on menu bar even after using hack

MacOS 11.4

**Comment by dragonwocky** [comment]
try https://github.com/notion-enhancer/notion-repackaged

**Comment by seba5496** [comment]
> try https://github.com/notion-enhancer/notion-repackaged

Hey there, I tried using the Notion Repackaged on Windows, but still no luck on getting the icon to show on the menu bar.

**Comment by dragonwocky** [comment]
can you show me a screenshot please?

**Comment by seba5496** [comment]
> can you show me a screenshot please?

Never mind, I just rebooted my system and now the logo is showing, feeling embarrassed now haha. 😬
Thanks anyway! 😊
