### ISSUE TITLE
(Windows) Can't open Notion even after hack

### ISSUE THREAD

**Issue by dragosescukiwi21** [notion-enhancer/notion-enhancer#534]
**describe the bug**
I can not open notion at all after completing this hack: _https://www.notion.so/hack-notion-enhancer-v0-10-2-to-work-with-notion-s-v2-0-13-app-a4ab1267e67b4126b6448641ca4a0041_

**screenshots**
This is what I get on task manager
![image](https://user-images.githubusercontent.com/29525524/125866229-b43f2d73-969c-4abd-8023-282c9d8c106c.png)

**platform**
I'm using windows 11

**Comment by dragonwocky** [comment]
try https://github.com/notion-enhancer/notion-repackaged

**Comment by zerorabb** [comment]
I have this issue.
I tried Notion Repackaged which opens, but the mods won't work.

**Comment by dragonwocky** [comment]
@zerorabb some of the mods have been fixed since (mainly themes). some of the ones by @CloudHill aren't working, an update will be released once we can sort out some problems with the build process.
