### ISSUE TITLE
warning Your file is over the limit of the Free plan

### ISSUE THREAD

**Issue by xaa** [notion-enhancer/notion-enhancer#535]
**Describe the bug**
priority low.

The red banner warning "Your file is over the 5MB limit of th Free Plan" doesn't dissapear and is visible on all pages. The app must be restarted to fix.

![](https://i.imgur.com/WsgorTW.png)

How to reproduce 
1) upload large picture (over 5MB)
2) navigate in other page. 
3) see the warning 

**expected behaviour**
Auto hide red warning. 
Display the warning on the specific page only

**platform**
Win10 21H1 19043.1083
Notion-enhancer latest version 0.10.2

**Comment by forrest-herman** [comment]
Can confirm I have the same issue. Even just a small [x] to dismiss in top left or right of the banner would be nice :)

**Comment by dragonwocky** [comment]
i think this is a notion default, not an enhancer bug?
