### ISSUE TITLE
Minimize, maximize and close icons are huge

### ISSUE THREAD

**Issue by forrest-herman** [notion-enhancer/notion-enhancer#536]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Minimize, maximize and close icons are huge! Can't figure out why. 

**expected behaviour**
Icons should be a normal size.

**screenshots**
![image](https://user-images.githubusercontent.com/58410716/126238922-7ef47c15-76a1-4394-989a-c781a9cfd0bc.png)
![image](https://user-images.githubusercontent.com/58410716/126238978-912ab852-1eda-422f-b986-e57caa902296.png)

**platform**
Windows 10

**Comment by biscuitowski** [comment]
Getting this too, so annoying, also dark theme doesn't apply anymore

**Comment by davelevine** [comment]
I had this same icon problem on Linux. It seemed to be caused by the "Integrated Titlebar" being turned on. Turning it off and then relaunching fixed it for me.

**Comment by esskayesss** [comment]
> Getting this too, so annoying, also dark theme doesn't apply anymore

I just installed it for the first time and hardly anything seems to work. Got a pretty bad impression of this.

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/291

@esskayesss sorry. school has taken priority over development at the moment, unfortunately.

**Comment by esskayesss** [comment]
@dragonwocky understandable mate...

**Comment by biscuitowski** [comment]
**### Fixed Temporary:** 

Replaced my Notion Accounts %AppData% from my work machine _(which had working notion + enhancer)_ into my Personal Machine _(which had issues after I reinstalled my whole system, notion + enhancer)_. And relaunching again. I guess the issue was somewhere there in the new installation file or update.
