### ISSUE TITLE
The theme feature of enhancer isn't working properly

### ISSUE THREAD

**Issue by TheOnlylight** [notion-enhancer/notion-enhancer#537]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
After full installation and the steps told to change the .js document in order to fix the bugs in 2.0.13+ problem, the enhancer seems to be capable of influence part of the system, but the theme feature is corrupted.

**expected behaviour**
why is this a bug - what should be happening?

After using the theme (toggle the dark) and restart the whole environment, during the startup, it seems to be applying the new theme like this:
![image](https://user-images.githubusercontent.com/24605645/126335017-af99b694-e84d-4538-8643-33e7641e78ff.png)
however after the full startup, the whole page will be forcebly changed into the white back ground mode, like this
![image](https://user-images.githubusercontent.com/24605645/126334987-71657d23-cd98-41af-af1c-16cb8c44ca5c.png)

the platform is win10 and the ver of the notion is 2.0.16.
two kinds of methods have been tried out, neither the packaged version nor the manually installed one works

**Comment by dragonwocky** [comment]
check your notion settings - is notion in light mode or dark mode?

**Comment by TheOnlylight** [comment]
> check your notion settings - is notion in light mode or dark mode?

Thanks a lot, I always thought the preferences should be upright cornered.LOL
