### ISSUE TITLE
Word Counter UI Bug

### ISSUE THREAD

**Issue by jamezcharazu** [notion-enhancer/notion-enhancer#541]
**describe the bug**
With 'word counter' enabled, there's a full-width circled '?' added to the document. Disabling removes it. With no other enhancements enabled, the bug still appears.

**expected behaviour**
The giant '?' is not meant to be there

**screenshots**
![image](https://user-images.githubusercontent.com/32897768/126979025-43db7ae3-1415-42f1-972f-71a5b659f9c6.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
caused by https://github.com/notion-enhancer/notion-enhancer/issues/291
