### ISSUE TITLE
Oversized icons with integrated titlebar enabled--without tabs.

### ISSUE THREAD

**Issue by jamezcharazu** [notion-enhancer/notion-enhancer#543]
**describe the bug**
With 'tabs' disabled and the 'integrated titlebar' enabled, the window option icons appear massively oversized.

**expected behaviour**
They should look as they do on a normal window, or as they do (for me) with 'tabs' enabled.

**screenshots**
Integrated Titlebar Enabled:
![image](https://user-images.githubusercontent.com/32897768/126980441-480ee3ae-264e-4d0b-9306-9eb61785fc98.png)

Integrated Titlebar Enabled with Tabs:
![image](https://user-images.githubusercontent.com/32897768/126980523-a19edb8f-ab4a-4c5c-b976-aa1b343f9d24.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-enhancer/issues/291
