### ISSUE TITLE
Big Title bar buttons and Themes are not applied.

### ISSUE THREAD

**Issue by MiliAxe** [notion-enhancer/notion-enhancer#544]
When I turn on the enhanced title bar mode, the title bar buttons are too big.

![Screenshot 2021-07-28 144832](https://user-images.githubusercontent.com/55515322/127306423-afecd3d5-5bae-4436-8618-110846f18a7a.png)

I am using windows 10 build 19043.1110 version 21H1

**Comment by MiliAxe** [comment]
I managed to fix this problem by turning off all options and only turning off this title bar option on.

**Comment by JackWenx** [comment]
I turn on tabs and it just covered the bug. LOL

**Comment by MiliAxe** [comment]
> 
> 
> I turn on tabs and it just covered the bug. LOL

It somehow got fixed after turning on and off the options. 🤷‍♂️
