### ISSUE TITLE
There are three big buttons on the titlebar

### ISSUE THREAD

**Issue by AlieZVzz** [notion-enhancer/notion-enhancer#547]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
There are three big buttons on the titlebar

**expected behaviour**
Everytime I open notion and enable integrated titlebar  

**screenshots**
![image](https://user-images.githubusercontent.com/47358078/127443791-a05bd514-de8d-47c4-87ff-f11912dd0596.png)

**platform**
Windows 10 20H2

**Comment by ZorkJ** [comment]
I have the same problem too.

**Comment by saeidscorp** [comment]
Same.

**Comment by mmmistgun** [comment]
same

**Comment by adityacryptota** [comment]
You need to go to: 
C:\Users\username\AppData\Roaming\npm\node_modules\notion-enhancer\mods\core

In the file **client.js**, go to around line number 122 and comment out this piece of code:
`if (!tabsEnabled) {
      const buttons = require('./buttons.js')(store);
      document
        .querySelector('.notion-topbar > div[style*="display: flex"]')
        .appendChild(buttons.element);
    }`

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/291
