### ISSUE TITLE
Notion Enhancer not working

### ISSUE THREAD

**Issue by sojuxd** [notion-enhancer/notion-enhancer#548]
I installed the notion enhancer in Windows 10 correctly cmd tells me its applied

But the enhancements menu hotkey (alt + e) doesn't seem to be working.

I already did the [hack](https://www.youtube.com/watch?v=vcwUpwpQ2sY) and its still not working

Notion Version: 2.0.16

**Comment by robinpdev** [comment]
Can you see notion enhancer in the system tray?

**Comment by sojuxd** [comment]
no i dont see

**Comment by YeshwanthRams** [comment]
Same.

It seems like the window bar changes are applied 
But I can't access the enhancer tool window by Alt + e In the current version of the notion:  2.0.16

**Comment by wacordoba** [comment]
I have the same problem on notion: 2.0.16

**Comment by Tilakbg90** [comment]
I had the same problem, reinstalling and adapting the hack did not work.

This did the trick for me (workaround for now):

1. Close notion desktop
2. Kill all notion background process
3. Delete notion folder in "C:\Users\xxxxx\AppData\Roaming\Notion"
4. Relaunch notion and login again

**Comment by sojuxd** [comment]
Did the Notion Enhancer work after that?

> I had the same problem, reinstalling and adapting the hack did not work.
> 
> This did the trick for me (workaround for now):
> 
> 1. Close notion desktop
> 2. Kill all notion background process
> 3. Delete notion folder in "C:\Users\xxxxx\AppData\Roaming\Notion"
> 4. Relaunch notion and login again

**Comment by zelev22** [comment]
> Did the Notion Enhancer work after that?

It did for me, give it a try.

Thank you so much, @Tilakbg90 !

**Comment by dragonwocky** [comment]
is it working for you yet? have you tried notion-repackaged?

**Comment by sojuxd** [comment]
> is it working for you yet? have you tried notion-repackaged?

Yes I've tried the [.exe](https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-2) repack, but the window controls are kinda messed up
