### ISSUE TITLE
Huge icons errywhere

### ISSUE THREAD

**Issue by KyryloKaralyus** [notion-enhancer/notion-enhancer#549]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
upon install, huge icons everywhere, independent of the enhancements

**expected behaviour**
normal icons
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.

**platform**
windows10
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

**Comment by dragonwocky** [comment]
see #291
