### ISSUE TITLE
Theme artifacts and errors

### ISSUE THREAD

**Issue by serjanbiogenic** [notion-enhancer/notion-enhancer#550]
**describe the bug**
After clean install of Notion-Enhanced-Setup-2.0.16-1.exe, massive icons appear
Themes do not work at all, it seems the app theme is divided into foreground and background, 
foreground is always Notion default dark theme that is not getting overwritten by the Enhancer. (pls see screenshot) 
Tried clean install with npm, Notion doesn't load at all. 

**expected behaviour**
normal icons, working themes

**screenshots**
massive icons:
https://drive.google.com/file/d/1W6NK03C-B_PUZo_WRQMAaTIGCqxubIPb/view?usp=sharing

theme issue:
https://drive.google.com/file/d/1W6QXYeyz0ZbY-wUCHrZNRACR-diBJahQ/view?usp=sharing

**platform**
Windows	10.0.19042 Build 19042

**Comment by dragonwocky** [comment]
see #291

**Comment by serjanbiogenic** [comment]
Tom, could you please suggest re the themes? Icons are fixed, but the theme issue is still there
