### ISSUE TITLE
Control button (min/max/close) looks "weird"

### ISSUE THREAD

**Issue by Rokakun** [notion-enhancer/notion-enhancer#552]
The Control button (min/max/close) looks glitchy

![2021-08-07_093105](https://user-images.githubusercontent.com/87281932/128609522-0eb1d9c1-b9d3-480d-ac7b-783071d971e8.png)

platform : windows 10

**Comment by Kcalb35** [comment]
yes, I met that bug too in the latest version 2.0.16-1

**Comment by Kcalb35** [comment]
I think something went wrong with the enhancement 'integrated titlebar'

**Comment by dragonwocky** [comment]
see #291
