### ISSUE TITLE
Adding custom colours for tags

### ISSUE THREAD

**Issue by Utsav-Murudi** [notion-enhancer/notion-enhancer#553]
**PROBLEM**

There are many people who colour code their stuff for better organization of data and pretty much everyone uses tags as fairly simple to use and very useful. But the limitation is that Notion has very less colours for tags(or any other thing for that matter)

**SOLUTION**

We can solve this by adding the ability to add custom colours.

**Comment by somyaSarathi** [comment]
Yes, option for custom Colors could be very usefull for organizing notes and documents.

**Comment by dragonwocky** [comment]
Out of scope / not doable. 

The enhancer can modify the appearance and to some degree the function of existing Notion content, but cannot add new content types.
