### ISSUE TITLE
Themes Not Work

### ISSUE THREAD

**Issue by ourainbows** [notion-enhancer/notion-enhancer#556]
I recently install enhancer, and themes not work, I tried reboot and poweoff my computer, uninstall and reinstall enhancer.
Previously I installed Notion App by pacman, but  I remove it before install enhancer

![image](https://user-images.githubusercontent.com/70644875/129435792-0571e9e2-49db-4395-9650-ed351d494392.png)

Garuda Linux (Distro bassed in arch)

**Comment by mike-mccormick** [comment]
Confirmed on MacOS using notion repackaged `Version 2.0.16-1 (2.0.16-1)`. 

Fresh installation on a fairly fresh install, with no copy of Notion installed prior.

![Notion](https://user-images.githubusercontent.com/2361501/129542162-cfa0bf3f-383d-45b7-a603-c03e4fed8cab.png)

**Comment by dragonwocky** [comment]
see #291

**Comment by mike-mccormick** [comment]
@dragonwocky outstanding! thank you for the fast response, and that sorted the issue! 🎉
