### ISSUE TITLE
bug on window buttons

### ISSUE THREAD

**Issue by miguelrisquelme** [notion-enhancer/notion-enhancer#558]
**describe the bug**
the buttons of windows are so strange

**expected behaviour**
the normal buttons of my system

**screenshots**
![image](https://user-images.githubusercontent.com/48338011/129565093-dcd33f2e-715f-41d5-ac67-124ae33e004e.png)

**platform**
Linux Mint 20.1 Cinamoon

**Comment by Veriox** [comment]
Same here

**Comment by Clagonova** [comment]
I was having the same issue but you can get rid of it by enabling "tabs" extension in enchantments menu (Alt+E)

**Comment by miguelrisquelme** [comment]
Press ALT + E

Just disable the option:
Integrated titlebar

![image](https://user-images.githubusercontent.com/48338011/129898319-2286a24a-3bed-4b22-b25b-edb907f2b25b.png)

![image](https://user-images.githubusercontent.com/48338011/129898432-966c3815-bfc8-4bbe-ada7-6bb4214ec34e.png)
