### ISSUE TITLE
Page Icons Are Broken in Tabs When Using Link Option

### ISSUE THREAD

**Issue by forrest-herman** [notion-enhancer/notion-enhancer#560]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Tab icons don't display if page icon is a link. (they only display if the icon is chosen as an emoji or an uploaded image)

**expected behaviour**
Icon should display in tabs regardless of emoji or upload or link type.

**screenshots**
![image](https://user-images.githubusercontent.com/58410716/129922801-10159a51-3d2b-45d7-9d5e-2512cc6e415e.png)
![image](https://user-images.githubusercontent.com/58410716/129922987-1f0577e4-54b2-4935-a32f-4f57776eac1f.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
how have you installed the enhancer? if you used the command line, I recommend switching to notion-repackaged (it may be fixed there).
