### ISSUE TITLE
Make tabbar and tabs titles smaller or collapsible

### ISSUE THREAD

**Issue by StLa1** [notion-enhancer/notion-enhancer#563]
**problem**

The tabbar is very tall and distracting.

**solution**
Add an option to make it small, or collapsible (expands on hover).

**cons**
I don't see any.

**Comment by saeidscorp** [comment]
Agreed. This would be very good. Especially with auto-hide capability.

**Comment by somyaSarathi** [comment]
Yes it would be very helpful.
