### ISSUE TITLE
notion out of memory

### ISSUE THREAD

**Issue by zydhhh** [notion-enhancer/notion-enhancer#564]
I‘d just met a critical problem that notion used out more than 21GB of memory which almost caused my Win10 crash. I could not tell more information because the process was killed and I don't know why it happened. 
The event viewer gives these:
Process_1 
   Name Notion.exe 
   ID 8204 
   CreationTime 2021-08-25T01:24:41.5262962Z 
   CommitCharge 22936657920 
   HandleCount 250 
   Version 2.0.16.0 
   TypeInfo 201 

BTW, I found when the tiling window manager mode's on the dragarea disappears. Is there any way to keep both of them?

**Comment by dragonwocky** [comment]
there's a memory leak somewhere, but we still have no idea where. sorry.

@zydhhh no - that mode is only meant to be used with tiling window managers where apps are not dragged around the screen or minimised etc. themselves, but are fully controlled by the window manager so the dragarea and buttons were just wasting space. if you want to be able to move the app with the dragarea, don't use that mode.
