### ISSUE TITLE
Window control broken

### ISSUE THREAD

**Issue by iJynx** [notion-enhancer/notion-enhancer#566]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Just installed notion enhanced. Window controls broken AF. See bellow.
![image](https://user-images.githubusercontent.com/60139910/131209036-3e79ddf4-cde1-4989-87f4-992febdf8d06.png)

**expected behaviour**
for it to be scaled normally.

**platform**
Windows 10

**Comment by dragonwocky** [comment]
see #291. a fix will be released in a day or 2.
