### ISSUE TITLE
Focus mode not working

### ISSUE THREAD

**Issue by marcoboh** [notion-enhancer/notion-enhancer#571]
**describe the bug**
Close/minimise/maximise buttons overlap share/update/favorite buttons. Focus mode works only with the close/minimise/maximise buttons, while share/update/favorite buttons are always shown.

**expected behaviour**
Share/update/favorite buttons shouldn't be shown with the focus mode, they also should be aside the close/minimise/maximise buttons, not overlapping them.

---

**screenshots**
### Bug screenshots
_Focus mode disabled_
![image](https://user-images.githubusercontent.com/55412676/131926449-5edec05d-0d87-4075-b130-ca6f733a0351.png)

_Focus mode enabled_
![image](https://user-images.githubusercontent.com/55412676/131926699-1a50ecf1-1cb0-499a-85d1-c086b2523967.png)

### Expected behaviour
_Focus mode disabled_
![image](https://user-images.githubusercontent.com/55412676/131926599-2c11c658-43b1-403d-b73c-62f2c3459f57.png)

_Focus mode enabled (just everything not shown)_
![image](https://user-images.githubusercontent.com/55412676/131926661-a003f5c0-13fb-4536-a18d-e0b02578b834.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
caused by https://github.com/notion-enhancer/notion-enhancer/issues/572
