### ISSUE TITLE
Title bar won't merge into one line.

### ISSUE THREAD

**Issue by gingerbreap** [notion-enhancer/notion-enhancer#575]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
The title bar won't merge to one line.

**screenshots**
![Snipaste_2021-09-07_11-14-21](https://user-images.githubusercontent.com/27958821/132278772-7354c726-2495-4dac-b130-4d97051419fd.png)

**platform**
Windows 10
![image](https://user-images.githubusercontent.com/27958821/132278918-05dd3dff-4e6f-42d3-8669-90b4c68ec3ad.png)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/572
