### ISSUE TITLE
How to get the same color for top bar and background?

### ISSUE THREAD

**Issue by khanhtuongle** [notion-enhancer/notion-enhancer#580]
**describe*:
Have a little difference between the original app and notion enhanced on the top bar. 

**screenshots**
![image](https://user-images.githubusercontent.com/89136898/132945235-13537c17-4ae8-4284-83e7-d5a0f54a23d1.png)
the notion enhanced on the right and original app on the left. Topbar of the original app is good-looking than the other.

**expected behaviour**
I hope it will have the same color as the original app because it makes colors sync

Thank you!

**Comment by dragonwocky** [comment]
this is intentional, as it matches the sidebar colour and differentiates between the draggable area and the main app area, so it will not be implemented as a feature directly in the enhancer. however, you could use a custom css insert to manually make it white:
```css
.frameless .window-dragarea {
  background: white !important;
}
```
