### ISSUE TITLE
Bug #extension ( right-to-left ) 

### ISSUE THREAD

**Issue by royalgold99** [notion-enhancer/notion-enhancer#591]
have problem in notion enhancer the problem is ( right-to-left ) #extension

**describe the bug**
 ( right-to-left ) #extension

**expected behavior**
not work it 

**screenshots**
I'm writing is an Arabic and in Arabic, we need writing in right to left

**platform**
What OS are you using? windows 10

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/589#issuecomment-927131258 for temporary solution
