### ISSUE TITLE
Eating up too much RAM (~6GB) on Windows

### ISSUE THREAD

**Issue by gdathuynh** [notion-enhancer/notion-enhancer#598]
It is eating too much RAM (~6GB) after I has been opened for 10hrs.

Version: 2.0.16-5
Platform: Windows 10

![image](https://user-images.githubusercontent.com/64056142/135449230-1aac261e-0e39-4f29-a5a5-45853c3396ec.png)

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/597
