### ISSUE TITLE
my "scroll to top" button suddenly disappear

### ISSUE THREAD

**Issue by joansheeran** [notion-enhancer/notion-enhancer#599]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

**Comment by l782993610** [comment]
change file /path to your notion-enhancer/mods/scroll-to-top/mod.js line 101 to
```
if (
                addedNodes[0] &&
                addedNodes[0].className === 'notion-scroller vertical horizontal' &&  //** target line **
                top > 0
              ) {
```

**Comment by l782993610** [comment]
It had been solve in a pull request #600

**Comment by joansheeran** [comment]
thank you so much!












徐琪
***@***.***


---Original---
From: ***@***.***&gt;
Date: Sat, Oct 2, 2021 15:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [notion-enhancer/notion-enhancer] my "scroll to top"buttonsuddenly disappear (#599)




 
change file /path to your notion-enhancer/mods/scroll-to-top/mod.js line 101 to
 if (                 addedNodes[0] &amp;&amp;                 addedNodes[0].className === 'notion-scroller vertical horizontal' &amp;&amp;  //** target line **                 top &gt; 0               ) {  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
