### ISSUE TITLE
outliner / table of contents not showing table of contents in the side panel

### ISSUE THREAD

**Issue by michealrm** [notion-enhancer/notion-enhancer#602]
**describe the bug**
I have side panel and outliner enabled. Currently it is not displaying headers that I have in my document on the side panel. Before, it was only showing on the first tab that I had, and any additional tabs I opened up the side panel would be blank, but now the side panel is never showing the table of contents.

**expected behaviour**
The expected behavior is that the table of contents show in the side panel. I'm also hoping that given a fix for this, table of contents would update when switching tabs, which was my first issue.

**screenshots**
![panel_bug_screenshot](https://user-images.githubusercontent.com/8922961/135728515-de843f3b-67eb-408b-bc9c-eae3201ee089.png)

**platform**
My operating system is Windows 10
I am using Notion Enhanced Repackaged 2.0.16 (rev 5)

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-enhancer/issues/596
