### ISSUE TITLE
RTL support doesn't work

### ISSUE THREAD

**Issue by AhmedHussien95** [notion-enhancer/notion-enhancer#608]
**describe the bug**
RTL support doesn't work

**expected behaviour**
The text should appear from right to left

**screenshots**
![Screenshot 2021-10-07 190555](https://user-images.githubusercontent.com/57030816/136422441-18bb676e-ba3c-4996-99d5-4091bbcdfd37.png)

**platform**
Win 11

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-enhancer/issues/589
