### ISSUE TITLE
The topbar Icons are extremelly big

### ISSUE THREAD

**Issue by joojscript** [notion-enhancer/notion-enhancer#623]
**describe the bug**
The topbar Icons are extremelly big.

**expected behaviour**
The topbar icons should have normal size.

**screenshots**
![image](https://user-images.githubusercontent.com/49156424/137776922-b7875533-1e1b-4a48-abd8-2ecfc74ec832.png)

![image](https://user-images.githubusercontent.com/49156424/137777016-97c50599-05ea-459b-8d79-e506bf0a4826.png)

**platform**
Linux Ubuntu 20.04.3 LTS (focal)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/291

@joojscript this is fixed in notion-repackaged, use that instead of patching with the command line.
