### ISSUE TITLE
Windows tops bar and horizontal scrollbar stay at the same time

### ISSUE THREAD

**Issue by Edemilorhea** [notion-enhancer/notion-enhancer#628]
Sorry, I don't know this problem is bug or it isn't.

But I really Want to close button, minimise, maximise can stay with horizontal scrollbar in fullpage table.

I try to many Time, if open integrated titlebar and close tiling window manger mode, scrollbar will loss.

If I open both options, I will lose windows top button

https://imgur.com/gallery/uMLajPe

**Comment by dragonwocky** [comment]
@Edemilorhea you should not enable tiling window manager mode. It is only for specialised setups where people do not want the minimise/maximise/close buttons.

Even if the scrollbar isn't visible, you can still scroll horizontally by holding `shift` and using the mouse mouse / touch pad to scroll. I'm not entirely understanding your problem, though, because everything is working fine for me?

**Comment by Edemilorhea** [comment]
> I don't really understand what you're trying to say.
> 
> Anyway, scrollbars are already fixed in the work-in-progress update and until then there are other ways to scroll across using the keyboard and mouse.

Sorry it's my bad, My English is not really good, So maybe let you can't understand my mean.

My main question is, if I don’t have a horizontal scroll bar, how can I drag left and right on a full-page table that is too wide.

Because I don’t understand, you said the way to hold down "SHIFT".

Thank you a lot

**Comment by dragonwocky** [comment]
Yep, that's it, use the mouse wheel.

**Comment by Edemilorhea** [comment]
> If you have a touchpad: swipe left/right across the touchpad.
> 
> If you have a mouse: hold down the `shift` key on your keyboard and at the same time use the scroll wheel on your mouse up or down. (Do not use the left/right mouse buttons.)

Yes!!!! Thank you  a lot, thank you for your patience, and I wish you a smooth development, I will continue to support your tools.
