### ISSUE TITLE
minimize, close and restore button disappeared, and taskar, and idk how to exit it, i deleted and reinstalled notion and restarted but its not working, 

### ISSUE THREAD

**Issue by Mariahahahahah** [notion-enhancer/notion-enhancer#642]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.
bug:
minimize, close and restore button disappeared, and taskbar and i don't know how to exit it, I deleted and reinstalled notion and restarted but it's not working, 

**expected behaviour**
the taskbar should show as it does all the time and so should the close x option, minimise and restore down

**screenshots**
notion image 
![image](https://user-images.githubusercontent.com/93684237/140197734-68c76f8f-18f7-4d1b-bf44-632629aabb20.png)

ctrl+shift+i, (inspect)
![image](https://user-images.githubusercontent.com/93684237/140198341-ce82bc5b-9a3d-4115-9eea-80c82495ce2c.png)

**platform**
windows 10

**Comment by dragonwocky** [comment]
how did you install the enhancer?

**Comment by Mariahahahahah** [comment]
Installed it through chrome  Sent from Mail for Windows From: TomSent: 03 November 2021 23:15To: notion-enhancer/notion-enhancerCc: Mariahahahahah; AuthorSubject: Re: [notion-enhancer/notion-enhancer] minimize, close and restore button disappeared, and taskar, and idk how to exit it, i deleted and reinstalled notion and restarted but its not working, (Issue #642) how did you install the enhancer?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mariahahahahah** [comment]
@dragonwocky installed it through chrome, no i didnt enable the tilin window manager

**Comment by dragonwocky** [comment]
@Mariahahahahah ...you can't install it through chrome. Did you use notion-repackaged or did you follow instructions from somewhere?

**Comment by Mariahahahahah** [comment]
i just searched up notion download on chrome and clicked download for windows (on this site https://www.notion.so/desktop)

**Comment by dragonwocky** [comment]
that is the official download that does not currently work with the enhancer, as the [installation instructions](https://github.com/notion-enhancer/notion-enhancer#installation) warn.

currently the only way to use the enhancer is to download and install the .exe from this page: https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-5

**Comment by Mariahahahahah** [comment]
that didn't fix the issue, but I played around with some buttons and eventually go it, thank you so much for your help!!!
