### ISSUE TITLE
Tabs Enhancer Feature Doesnt Load

### ISSUE THREAD

**Issue by QueenEvanescence** [notion-enhancer/notion-enhancer#644]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING ALL NON-BOLD TEXT WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
When i enable tab feature and relaunch notion it doesnt load, just shows a dark grey screen with loading circle
I have only a few basic core features enabled
Also my Notion is in light mode but on enablng the tab feature the Enhancer screen as well notion becomes dark mode(?!?) 
On disabling the feature it reverts to light mode
**expected behaviour**
its supposed to load and only additional feature is the tabs
notion should continue to remain in light mode

**screenshots**
<img width="1920" alt="2021-11-04 (2)" src="https://user-images.githubusercontent.com/88851719/140391407-fa2c47ce-e64d-4617-9869-0dfc1f67b789.png">

**platform**
Im currently using Windows 10 and my notion version is 2.0.18

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/606
