### ISSUE TITLE
topbar navigation blocked by search modal

### ISSUE THREAD

**Issue by brennanafrank** [notion-enhancer/notion-enhancer#713]
**What is happening?**

The links in the up-top bar (the navigation ones) are not working starting some amount of time after a page loads. They are not clickable. Also, the "sandwich menu" in the upper left corner is not working.

**What should be happening?**

These links I've described should be clickable.

**Screenshots (if applicable):**

<img width="474" alt="image" src="https://user-images.githubusercontent.com/66388912/149673188-ab3a089b-075c-4788-8bc2-1afd069e800b.png">

**Operating system/browser name & version:**

Windows 10 Pro Version 20H2

**notion-enhancer and/or notion-repackaged version:**

Notion-Enhancer desktop v0.11.0

**notion-enhancer configuration (enabled/disabled mods and their settings):**

pastel dark theme, tabs enabled with compact tab layout, code line numbers, everything else disabled

edit 1:42pm EST - and emoji sets, forgot about that one

**Comment by dragonwocky** [comment]
do any other buttons in the topbar work (e.g. the breadcrumb)?

does this only happen in the desktop app or also in the browser?

**Comment by brennanafrank** [comment]
I only use the desktop version of Notion, so I wouldn't be able to tell you whether this issue is specific to the desktop version.

I haven't been able to recreate the error, but it had been doing that after multiple reboots of the application. I recall that the "search tool" worked, and I was able to click that. Everything to the left of that, however, was unresponsive.

**Comment by brennanafrank** [comment]
After more experimentation, it seems the issue is not as pressing as I thought. Notion Enhanced Desktop simply doesn't seem to let you use those navigation links while the _Ctrl-F_ search box is on-screen.

The standard version of Notion Desktop lets you do this, so maybe it is a bug and still deserves reporting.

**Comment by dragonwocky** [comment]
ah, `ctrl+f` intefering makes sense. does it only happen when tabs are enabled, or just anytime you open the search box?

> The standard version of Notion Desktop lets you do this, so maybe it is a bug and still deserves reporting.
yep, still a bug, even if it's not a major one
