### ISSUE TITLE
Custom Icon Integrate Mod is Break

### ISSUE THREAD

**Issue by Apolsus** [notion-enhancer/notion-enhancer#767]
The Custom Icon Integrate Mod is Break, The custom icon cannot be set properly when clicked.

Environment: all platform
 
Notion Version: 2.17.23.10.25.57

Enhancer Version: 11

But fortunately, I know why and how to fix it.

In file 'client.js' line 119, delete the variable 'uploadTab' and related code. The 'linkTab' is now the second tab, modify this.

```js
   const $emojiTab = document.querySelector(tabBtnSelector(1)),
      $emojiScroller = document.querySelector(mediaScrollerSelector),
      $emojiFilter = document.querySelector(mediaFilterSelector),
      $linkTab = document.querySelector(tabBtnSelector(2));

    $linkTab.style.display = 'none';
    if ($activeTabUnderline) $activeTabUnderline.remove();
    $activeTabUnderline =
      $emojiTab.children[1] || $linkTab.children[1];
    $emojiTab.after($iconsTab);
    $emojiScroller.after($iconsView);
```

**Comment by elbyte** [comment]
Also having the issue, and it's quite the nuisance. Would love this fix to be implemented!
