### ISSUE TITLE
Weekly calendar view fail

### ISSUE THREAD

**Issue by yolearn** [notion-enhancer/notion-enhancer#829]
Why my calendar view failed?

![image](https://user-images.githubusercontent.com/16368433/166925776-2d8abca6-2ab3-4034-8b5a-e98960b0257c.png)
https://www.notion.so/26ba65d5f9fb43b1bcfccd9ef3902be6?v=afe78a03f2cd4888a2767324edf3752f

**Comment by dmercado2001** [comment]
also still an issue for me, both in the app version and chrome extension version

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-enhancer/issues/751
