### ISSUE TITLE
Hide toggles for empty pages

### ISSUE THREAD

**Issue by KaiStarkk** [notion-enhancer/notion-enhancer#847]
As discussed by @admiraldus [here](https://www.reddit.com/r/Notion/comments/k0v2xa/comment/gdkz3u6/?context=3)

**What makes the feature necessary?**
Visual clutter in the sidebar makes organizing projects on Notion cumbersome - this particular behaviour is quite clutter-y.
![DYNNCU8 1](https://user-images.githubusercontent.com/1722064/154624795-c66e533d-966c-4038-a34d-4c59a328f0c3.png)

**How would the feature work?**
This would be an extention with no options. When enabled, the sidebar would suppress toggle arrows for pages with no subpages.

**Comment by dragonwocky** [comment]
I think this is a solved by the latest updates Notion has made to their interface? If you hover over the page icon, it turns into an arrow that will toggle the "No pages inside" dropdown, but the rest of the time there is no arrow visible and no clutter to be cumbered by.
![image](https://github.com/notion-enhancer/notion-enhancer/assets/16874139/8815f199-0bc9-43c9-a801-7ddb7bcccc95)
